ejb-multi-server/app-main/ejb/src/main/java/org/jboss/as/quickstarts/ejb/multi/server/app/MainAppBean.java, ejb-multi-server/app-main/ejb/src/main/java/org/jboss/as/quickstarts/ejb/multi/server/app/MainAppSContextBean.java, ejb-multi-server/app-main/web/src/main/java/org/jboss/as/quickstarts/ejb/multi/server/app/JsfController.java, ejb-multi-server/app-web/src/main/java/org/jboss/as/quickstarts/web/multi/server/app/Servlet.java, ejb-multi-server/client/src/main/java/org/jboss/as/quickstarts/ejb/multi/server/Client.java, ejb-multi-server/deploy-domain.cli, ejb-multi-server/install-domain.cli, ejb-multi-server/undeploy-domain.cli
https://issues.jboss.org/browse/WFLY-4301
note that the quickstart can not run correct until https://issues.jboss.org/browse/WFLY-4299 is fixed
=> WFLY-4301  correct project after the maven artifactId change

guide/KitchensinkQuickstart.asciidoc
@Model annotation adds @Named & @RequestScoped to a class.
=> Fix typo: Should be @Model instead of @Member

helloworld-mdb/README.md
hornetq-jms.xml is no longer used in this project - destinations are created via annotations
=> Updated destinations creation process description

ejb-multi-server/install-domain.cli
Adjust script for new subsystem batch-jberet
=> ejb-multi-server: adjust quickstart for batch-jberet subsystem

helloworld-ssl/README.md, helloworld-ssl/pom.xml, helloworld-ssl/src/main/java/org/jboss/as/quickstarts/helloworld/HelloService.java, helloworld-ssl/src/main/java/org/jboss/as/quickstarts/helloworld/HelloWorldServlet.java, helloworld-ssl/src/main/webapp/WEB-INF/beans.xml, helloworld-ssl/src/main/webapp/WEB-INF/web.xml, helloworld-ssl/src/main/webapp/index.html, pom.xml
This is first and simplest example (wildfly ssl configuration) in the wildlfy-ssl series. It will be followed by 
1. Mutual (two way) ssl authentication for clients over wildfly
2. Securing war (client) apps over wildlfy
3. Some other security tweaks/mechanisms with wildfly.
=> helloworld-ssl example to demonstrate ssl configuration over wildfly.

pom.xml, websocket-client/LICENSE.txt, websocket-client/README.md, websocket-client/pom.xml, websocket-client/src/main/java/org/jboss/as/quickstarts/websocket/client/Backend.java, websocket-client/src/main/java/org/jboss/as/quickstarts/websocket/client/ConnectionGate.java, websocket-client/src/main/java/org/jboss/as/quickstarts/websocket/client/Frontend.java, websocket-client/src/main/java/org/jboss/as/quickstarts/websocket/client/SessionManager.java, websocket-client/src/main/java/org/jboss/as/quickstarts/websocket/client/SessionMessage.java, websocket-client/src/main/java/org/jboss/as/quickstarts/websocket/client/ToBackend.java, websocket-client/src/main/java/org/jboss/as/quickstarts/websocket/client/ToBroadcast.java, websocket-client/src/main/java/org/jboss/as/quickstarts/websocket/client/ToFrontend.java, websocket-client/src/main/webapp/WEB-INF/beans.xml, websocket-client/src/main/webapp/index.html
A websocket client quickstart.  The README has the full description.  I tried to follow all the contributing guidelines.
=> websocket-client quickstart

helloworld-rs/README.md
The access URLs in the readme file were not updated.
=> Updated README.md with correct access URL.

ejb-multi-server/install-domain.cli
It seems that the CLI syntax for "thread" and "workmanager" entries has changed.
The CLI commands need to be adjusted
=> JBEAP-2831: can not configure domain in ejb-multi-server QS

cdi-interceptors/src/main/java/org/jboss/as/quickstarts/cdi/service/ItemBean.java
Wrong checking for empty string
=> no error when name is empty

cdi-interceptors/README.md
=> wrong link in readme to deployed war

ejb-multi-server/install-domain.cli
Configuration change.
https://issues.jboss.org/browse/WFLY-7182
=> WFLY-7182 Server configuration has not been migrated after renaming the application

thread-racing/src/main/java/org/jboss/as/quickstarts/threadracing/stage/jms/JMSRaceStage.java
Injected JMSContext are not supported when call is coming from a
WebSocket endpoint as they do not define CDI scope for managed bean (as
reported in https://issues.jboss.org/browse/CDI-370 and
https://java.net/jira/browse/WEBSOCKET_SPEC-196).
Instead, look up the default JMS ConnectionFactory and create an
application-managed JMSContext in a try-with-resources block.
=> Do not use injected JMSContext

ha-singleton-service/README.md, ha-singleton-service/name-preference-election-policy-add.cli, ha-singleton-service/pom.xml, ha-singleton-service/primary-only/pom.xml, ha-singleton-service/primary-only/src/main/java/org/jboss/as/quickstarts/ha/singleton/service/primary/QueryingService.java, ha-singleton-service/primary-only/src/main/java/org/jboss/as/quickstarts/ha/singleton/service/primary/ServiceActivator.java, ha-singleton-service/primary-only/src/main/java/org/jboss/as/quickstarts/ha/singleton/service/primary/SingletonService.java, ha-singleton-service/primary-only/src/main/resources/META-INF/services/org.jboss.msc.service.ServiceActivator, ha-singleton-service/quorum-add.cli, ha-singleton-service/quorum-remove.cli, ha-singleton-service/random-election-policy-add.cli, ha-singleton-service/with-backups/pom.xml, ha-singleton-service/with-backups/src/main/java/org/jboss/as/quickstarts/ha/singleton/service/backups/ServiceActivator.java, ha-singleton-service/with-backups/src/main/java/org/jboss/as/quickstarts/ha/singleton/service/backups/SingletonService.java, ha-singleton-service/with-backups/src/main/resources/META-INF/services/org.jboss.msc.service.ServiceActivator, pom.xml
Jira
https://issues.jboss.org/browse/WFLY-8541
=> WFLY-8541 Create SingletonService quickstart

messaging-clustering-singleton/README.md, messaging-clustering-singleton/disable-delivery-group-domain.cli, messaging-clustering-singleton/disable-delivery-group-standalone.cli, messaging-clustering-singleton/enable-delivery-group-domain.cli, messaging-clustering-singleton/enable-delivery-group-standalone.cli, messaging-clustering-singleton/install-domain.cli, messaging-clustering-singleton/install-standalone.cli, messaging-clustering-singleton/pom.xml, messaging-clustering-singleton/remove-domain.cli, messaging-clustering-singleton/remove-standalone.cli, messaging-clustering-singleton/restart-node1-domain.cli, messaging-clustering-singleton/restart-node2-domain.cli, messaging-clustering-singleton/src/main/java/org/jboss/as/quickstarts/mdb/HelloWorldQueueMDB.java, messaging-clustering-singleton/src/main/java/org/jboss/as/quickstarts/mdb/HelloWorldTopicMDB.java, messaging-clustering-singleton/src/main/java/org/jboss/as/quickstarts/servlet/HelloWorldMDBServletClient.java, messaging-clustering-singleton/src/main/webapp/WEB-INF/beans.xml, messaging-clustering-singleton/src/main/webapp/WEB-INF/jboss-ejb3.xml, messaging-clustering-singleton/src/main/webapp/index.html, messaging-clustering-singleton/undeploy-domain.cli, messaging-clustering-singleton/undeploy-standalone.cli
Quickstart for message-clustering-singleton.
WFLY Jira: https://issues.jboss.org/browse/WFLY-8976
EAP7 Jira: https://issues.jboss.org/browse/EAP7-714
=> [WFLY-8976] Add new quickstart for message-clustering-singleton

guide/GettingStarted.asciidoc
The top part of the readme says Java 7, the Getting Started part needs "1.8.0" meaning Java 8, so I updated the Java 7 to 8 at the top.
=> Changed Java 7 to Java 8

helloworld-mutual-ssl-secured/README.md, helloworld-mutual-ssl-secured/configure-ssl.cli, helloworld-mutual-ssl/README.md, helloworld-mutual-ssl/configure-ssl.cli, helloworld-mutual-ssl/src/main/webapp/index.html, helloworld-ssl/README.md, helloworld-ssl/configure-ssl.cli
Issues fixed:
https://issues.jboss.org/browse/JBEAP-12588
https://issues.jboss.org/browse/JBEAP-12597
https://issues.jboss.org/browse/JBEAP-12572
=> Fixes for the SSL related quickstarts

deltaspike-authorization/pom.xml, deltaspike-beanbuilder/pom.xml, deltaspike-projectstage/pom.xml, pom.xml, template/pom.xml, wicket-ear/pom.xml
There were 3 spots I removed a previously defined version. If this is incorrect please let me know and I'll fix it.
=> Upgrade the wildfly-maven-plugin to 1.2.0.Beta1

ha-singleton-service/README.md
https://issues.jboss.org/browse/WFLY-9426
=> WFLY-9426 ISPN000065 in ha-singleton-service QS

resteasy-jaxrs-client/pom.xml
https://issues.jboss.org/browse/JBEAP-14298
=> [JBEAP-14298] Resteasy client quickstart dependency fix

pom.xml
jboss-parent bump to version 26
=> jboss-parent bump to version 26

pom.xml
https://issues.jboss.org/browse/WFLY-9984
=> [WFLY-9984] add required workaround change for JDK-9 use

jaxws-addressing/client/pom.xml, jaxws-ejb/client/pom.xml, jaxws-pojo/client/pom.xml, jaxws-retail/client/pom.xml
jaxws-* client fixes to run on JDK 11
=> jaxws-* client fixes to run on JDK 11

ejb-security-context-propagation/src/main/java/org/jboss/as/quickstarts/ejb_security_context_propagation/RemoteClient.java
JIRA: https://issues.jboss.org/browse/WFLY-10514
=> WFLY-10514: fixes admin user credentials hardcode in client, to match docs

spring-greeter/src/main/java/org/jboss/spring/quickstarts/greeter/greeter_spring/domain/UserDaoImpl.java
JIRA: https://issues.jboss.org/browse/WFLY-10546
=> WFLY-10546: spring-greeter user query supported by both EE7 and EE8

spring-resteasy/README.adoc, spring-resteasy/src/main/java/org/jboss/as/quickstarts/resteasyspring/HelloSpringResource.java, spring-resteasy/src/test/java/org/jboss/as/quickstarts/resteasyspring/test/ResteasySpringIT.java
JIRA: https://issues.jboss.org/browse/WFLY-10548
=> WFLY-10548: removes hardcoded URLs and fixes doc

inter-app/README.adoc, inter-app/appA/src/main/java/org/jboss/as/quickstarts/interapp/appA/Imports.java, inter-app/appB/src/main/java/org/jboss/as/quickstarts/interapp/appB/Imports.java
JIRA: https://issues.jboss.org/browse/WFLY-11210
=> WFLY-11210: replaces EJB annotations with JNDI lookups

jaxws-retail/service/log4j.properties, jaxws-retail/service/pom.xml
WFLY JIRA: https://issues.jboss.org/browse/WFLY-11209
JBEAP JIRA: https://issues.jboss.org/browse/JBEAP-15215
=> WFLY-11209: adds log4j config to jaxws-tools-maven-plugin execution

jaxws-addressing/client/pom.xml, jaxws-ejb/client/pom.xml, jaxws-pojo/client/pom.xml, jaxws-retail/client/pom.xml, jaxws-retail/service/pom.xml, pom.xml
JIRA: https://jira.jboss.org/browse/WFLY-11266
Depends on wildfly/boms#47
=> WFLY-11266: introducing jaxws client bom

template/README.adoc
=> WFLY-11312: Update template README file to note that CD instructions are not included in the template

README.adoc, ejb-multi-server/README.adoc, ejb-security-context-propagation/README.adoc, ejb-security-jaas/README.adoc, ejb-security-programmatic-auth/README.adoc, ejb-security/README.adoc, ha-singleton-deployment/README.adoc, ha-singleton-service/README.adoc, helloworld-jms/README.adoc, helloworld-mdb-propertysubstitution/README.adoc, helloworld-mutual-ssl-secured/README.adoc, helloworld-mutual-ssl/README.adoc, helloworld-ssl/README.adoc, http-custom-mechanism/README.adoc, jaxrs-jwt/README.adoc, jts/README.adoc, logging/README.adoc, mail/README.adoc, messaging-clustering-singleton/README.adoc, messaging-clustering/README.adoc, security-domain-to-domain/README.adoc, servlet-security/README.adoc, shared-doc/attributes.adoc, shared-doc/install-quickstart-parent-artifact.adoc, shared-doc/suggested-approach.adoc, shared-doc/system-requirements.adoc, shopping-cart/README.adoc, template/README.adoc
JIRA: https://issues.jboss.org/browse/WFLY-11477
=> WFLY-11477: Update root README.adoc to be more readable for WildFly and to include build instructions

ee-security/README.adoc, ee-security/configure-elytron.cli, ee-security/pom.xml, ee-security/restore-configuration.cli, ee-security/src/main/java/org/jboss/as/quickstarts/ee_security/ElytronIdentityStore.java, ee-security/src/main/java/org/jboss/as/quickstarts/ee_security/SecuredServlet.java, ee-security/src/main/java/org/jboss/as/quickstarts/ee_security/SecurityFactory.java, ee-security/src/main/java/org/jboss/as/quickstarts/ee_security/TestAuthenticationMechanism.java, ee-security/src/main/webapp/WEB-INF/beans.xml, pom.xml
@emmartins : @darranl suggested I open this PR to replace https://github.com/wildfly/quickstart/pull/326. Feel free to close this one if you prefer I make the updates separately.
=> JIRA: https://issues.jboss.org/browse/WFLY-7186

jts/application-component-2/src/main/resources/META-INF/jboss-ejb3.xml
JIRA: https://issues.jboss.org/browse/WFLY-11618
=> WFLY-11618: fixes jts quickstart

helloworld-mdb-propertysubstitution/README.adoc, helloworld-mdb/README.adoc
Issue: https://issues.jboss.org/browse/WFLY-11643
=> [WFLY-11643][JBEAP-16289] Update the console messages for helloworld-mdb and helloworld-mdb-propertysubstitution quickstarts

shared-doc/attributes.adoc
Issue: https://issues.jboss.org/browse/WFLY-11883
=> [WFLY-11883] fixes DocInfoProductName shared docs attr

README.adoc
Issue: https://issues.jboss.org/browse/WFLY-11812
=> [WFLY-11812] command to build docs should be mvn clean package -Pdocs

messaging-clustering-singleton/install-standalone.cli, messaging-clustering-singleton/remove-standalone.cli, messaging-clustering/install-standalone.cli, messaging-clustering/remove-standalone.cli
JIRA: https://issues.jboss.org/browse/WFLY-9977
=> WFLY-9977: CLI scripts to install and remove standalone configurations do not need to enable the CONSOLE

jaxws-retail/README.adoc
JIRA: https://issues.jboss.org/browse/WFLY-11049
=> JBEAP-11049: jaxws-retail quickstart displays console errors when using JDK 11

ejb-security/README.adoc
https://issues.jboss.org/browse/WFLY-12053
=> [WFLY-12053] Update the ejb-security quickstart README to make it more clear that a user needs to be added before running it

xml-jaxp/src/main/java/org/jboss/as/quickstart/xml/XMLParser.java
https://issues.jboss.org/browse/WFLY-12015
https://issues.jboss.org/browse/JBEAP-16512
=> [WFLY-12015] WFLYUT0017 warning appears once xml-jaxp quickstart is undeployed

jaxws-ejb/service/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12198
=> [WFLY-12198] Remove unused dependency on Quickstart jaxws-ejb

pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12199
=> [WFLY-12199] Remove import of Quickstarts BOM

tasks-rs/README.adoc
Issue: https://issues.jboss.org/browse/WFLY-12262
=> [WFLY-12262] remove tasks-rf readme pre-requisite

pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12288
=> [WFLY-12288] Re-add jboss public maven repo

bmt/pom.xml, cmt/pom.xml, deltaspike-authorization/pom.xml, deltaspike-beanbuilder/pom.xml, deltaspike-projectstage/pom.xml, ee-security/pom.xml, greeter/pom.xml, jta-crash-rec/pom.xml, jts/application-component-1/pom.xml, jts/application-component-2/pom.xml, managed-executor-service/pom.xml, spring-kitchensink-basic/pom.xml, spring-kitchensink-springmvctest/pom.xml, template/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12490
=> [WFLY-12490] Propagating changes from WFLY-12460 and WFLY-12418

pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12494
=> [WFLY-12494] add product maven repository

pom.xml, template/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12468
=> [WFLY-12468] Rename BOMs artifactIds with javaee8-* to jakartaee8-*

jaxws-addressing/client/pom.xml, jaxws-ejb/client/pom.xml, jaxws-pojo/client/pom.xml, jaxws-retail/client/pom.xml, jaxws-retail/service/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12377
=> [WFLY-12377] Document usage of JAXWS Client BOM in jaws-* quickstarts

app-client/client-simple/pom.xml, ejb-asynchronous/client/pom.xml, ejb-multi-server/client/pom.xml, ejb-remote/client/pom.xml, ejb-security-context-propagation/pom.xml, ejb-security-jaas/pom.xml, ejb-security-programmatic-auth/pom.xml, ejb-security/pom.xml, helloworld-jms/pom.xml, shopping-cart/client/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-12630
=> WFLY-12630: Document usage of EJB and JMS Client BOM in Quickstarts

spring-greeter/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13021
=> WFLY-13021 adding servlet dependency in pom.xml

batch-processing/src/main/java/org/jboss/as/quickstarts/batch/controller/JobData.java
Issue: https://issues.redhat.com/browse/WFLY-12093
=> [WFLY-12093]"bug in tutorial "batch-processing" with column "End Time"

shared-doc/attributes.adoc
Issue: https://issues.redhat.com/browse/JBEAP-18693
=> [JBEAP-18693] moves to next CD version in docs attributes

messaging-clustering-singleton/src/main/webapp/WEB-INF/jboss-ejb3.xml
Issue: https://issues.redhat.com/browse/WFLY-13031
=> [WFLY-13031] EAP quickstart 'messaging-clustering-singleton' shows errors after import

microprofile-config/README.adoc, microprofile-config/pom.xml, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/ConfigResource.java, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/ConverterResource.java, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/CustomConfigResource.java, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/JaxRsApplication.java, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/converter/MicroProfileCustomValueConverter.java, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/converter/type/MicroProfileCustomValue.java, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/custom/CustomConfigSource.java, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/custom/CustomPropertiesFileProvider.java, microprofile-config/src/main/resources/META-INF/microprofile-config.properties, microprofile-config/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource, microprofile-config/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSourceProvider, microprofile-config/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter, microprofile-config/src/main/webapp/WEB-INF/web.xml, microprofile-config/src/main/webapp/index.jsp, microprofile-config/src/test/java/org/wildfly/quickstarts/microprofile/config/MicroProfileConfigIT.java, microprofile-config/src/test/resources/arquillian.xml, pom.xml
https://issues.redhat.com/browse/WFLY-12802
Branch 19.0.x
=> [19.x] [WFLY-12802] Quickstart for MP Config 1.4

microprofile-rest-client/README.adoc, microprofile-rest-client/country-client/pom.xml, microprofile-rest-client/country-client/src/main/java/org/wildfly/quickstarts/microprofile/rest/client/CountriesResource.java, microprofile-rest-client/country-client/src/main/java/org/wildfly/quickstarts/microprofile/rest/client/CountriesServiceClient.java, microprofile-rest-client/country-client/src/main/java/org/wildfly/quickstarts/microprofile/rest/client/JaxRsApplication.java, microprofile-rest-client/country-client/src/main/java/org/wildfly/quickstarts/microprofile/rest/client/NotFoundResponseExceptionMapper.java, microprofile-rest-client/country-client/src/main/java/org/wildfly/quickstarts/microprofile/rest/client/model/Country.java, microprofile-rest-client/country-client/src/main/resources/META-INF/microprofile-config.properties, microprofile-rest-client/country-client/src/test/java/org/wildfly/quickstarts/microprofile/rest/client/MicroProfileRESTClientIT.java, microprofile-rest-client/country-client/src/test/java/org/wildfly/quickstarts/microprofile/rest/client/api/CountryProviderResource.java, microprofile-rest-client/country-client/src/test/java/org/wildfly/quickstarts/microprofile/rest/client/api/JaxRsApplication.java, microprofile-rest-client/country-client/src/test/resources/arquillian.xml, microprofile-rest-client/country-server/pom.xml, microprofile-rest-client/country-server/src/main/java/org/wildfly/quickstarts/microprofile/Country.java, microprofile-rest-client/country-server/src/main/java/org/wildfly/quickstarts/microprofile/CountryProviderResource.java, microprofile-rest-client/country-server/src/main/java/org/wildfly/quickstarts/microprofile/JaxRsApplication.java, pom.xml
https://issues.redhat.com/browse/WFLY-12823
Branch 19.0.x
=> [19.x] [WFLY-12823] Quickstart for MP REST-client 1.4

microprofile-rest-client/README.adoc
https://issues.redhat.com/browse/WFLY-12823
Branch 19.0.x
=> [WFLY-12823] Fix README guide in the quickstart for MP REST-client

microprofile-opentracing/README.adoc, microprofile-opentracing/pom.xml, microprofile-opentracing/src/main/java/org/wildfly/quickstarts/microprofile/opentracing/ExplicitlyTracedBean.java, microprofile-opentracing/src/main/java/org/wildfly/quickstarts/microprofile/opentracing/JaxRsApplication.java, microprofile-opentracing/src/main/java/org/wildfly/quickstarts/microprofile/opentracing/TracedResource.java, microprofile-opentracing/src/test/java/org/wildfly/quickstarts/microprofile/opentracing/MicroProfileOpenTracingIT.java, microprofile-opentracing/src/test/java/org/wildfly/quickstarts/microprofile/opentracing/MockTracerResolver.java, microprofile-opentracing/src/test/resources/arquillian.xml, pom.xml
https://issues.redhat.com/browse/WFLY-12829
Branch 19.0.x
=> [19.x] [WFLY-12829] Quickstart for MP OpenTracing 1.3

microprofile-openapi/README.adoc, microprofile-openapi/pom.xml, microprofile-openapi/src/main/java/org/wildfly/quickstart/microprofile/openapi/Fruit.java, microprofile-openapi/src/main/java/org/wildfly/quickstart/microprofile/openapi/FruitResource.java, microprofile-openapi/src/main/java/org/wildfly/quickstart/microprofile/openapi/InventoryApplication.java, microprofile-openapi/src/main/webapp/WEB-INF/web.xml, pom.xml
https://issues.redhat.com/browse/WFLY-13207
=> [19.0.x] WFLY-13207 Quickstart for MP OpenAPI 1.1.2

microprofile-metrics/README.adoc, microprofile-metrics/grafana.json, microprofile-metrics/pom.xml, microprofile-metrics/prometheus.yml, microprofile-metrics/src/main/java/org/wildfly/quickstarts/microprofile/metrics/JaxRsApplication.java, microprofile-metrics/src/main/java/org/wildfly/quickstarts/microprofile/metrics/PrimeNumberChecker.java, microprofile-metrics/src/test/java/org/wildfly/quickstarts/microprofile/metrics/MicroProfileMetricsIT.java, microprofile-metrics/src/test/resources/arquillian.xml, pom.xml
https://issues.redhat.com/browse/WFLY-12809
=> [WFLY-12809] Quickstart for MP Metrics 2.3

microprofile-openapi/README.adoc, microprofile-openapi/pom.xml, microprofile-openapi/src/main/java/org/wildfly/quickstart/microprofile/openapi/Fruit.java, microprofile-openapi/src/main/java/org/wildfly/quickstart/microprofile/openapi/FruitResource.java, microprofile-openapi/src/main/java/org/wildfly/quickstart/microprofile/openapi/InventoryApplication.java, microprofile-openapi/src/main/webapp/WEB-INF/web.xml, pom.xml
https://issues.redhat.com/browse/WFLY-13207
=> WFLY-13207 Quickstart for MP OpenAPI 1.1.2

microprofile-rest-client/README.adoc, microprofile-rest-client/country-client/pom.xml, microprofile-rest-client/country-client/src/main/java/org/wildfly/quickstarts/microprofile/rest/client/CountriesResource.java, microprofile-rest-client/country-client/src/main/java/org/wildfly/quickstarts/microprofile/rest/client/CountriesServiceClient.java, microprofile-rest-client/country-client/src/main/java/org/wildfly/quickstarts/microprofile/rest/client/JaxRsApplication.java, microprofile-rest-client/country-client/src/main/java/org/wildfly/quickstarts/microprofile/rest/client/NotFoundResponseExceptionMapper.java, microprofile-rest-client/country-client/src/main/java/org/wildfly/quickstarts/microprofile/rest/client/model/Country.java, microprofile-rest-client/country-client/src/main/resources/META-INF/microprofile-config.properties, microprofile-rest-client/country-client/src/test/java/org/wildfly/quickstarts/microprofile/rest/client/MicroProfileRESTClientIT.java, microprofile-rest-client/country-client/src/test/java/org/wildfly/quickstarts/microprofile/rest/client/api/CountryProviderResource.java, microprofile-rest-client/country-client/src/test/java/org/wildfly/quickstarts/microprofile/rest/client/api/JaxRsApplication.java, microprofile-rest-client/country-client/src/test/resources/arquillian.xml, microprofile-rest-client/country-server/pom.xml, microprofile-rest-client/country-server/src/main/java/org/wildfly/quickstarts/microprofile/Country.java, microprofile-rest-client/country-server/src/main/java/org/wildfly/quickstarts/microprofile/CountryProviderResource.java, microprofile-rest-client/country-server/src/main/java/org/wildfly/quickstarts/microprofile/JaxRsApplication.java, pom.xml
https://issues.redhat.com/browse/WFLY-12823
=> [WFLY-12823] Quickstart for MP REST-client 1.4

microprofile-config/pom.xml, microprofile-health/pom.xml, microprofile-metrics/pom.xml, microprofile-rest-client/country-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13258
=> [19.0.x] [WFLY-13258] replace commons-logging

microprofile-config/pom.xml, microprofile-health/pom.xml, microprofile-metrics/pom.xml, microprofile-rest-client/country-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13258
=> [WFLY-13258] replace commons-logging

microprofile-openapi/README.adoc
Issue: https://issues.redhat.com/browse/WFLY-13398
=> [19.0.x] [WFLY-13398] adds missing attributes to mp openapi quickstart readme

microprofile-openapi/README.adoc
Issue: https://issues.redhat.com/browse/WFLY-13398
=> [WFLY-13398] adds missing attributes to mp openapi quickstart readme

deltaspike-authorization/pom.xml, http-custom-mechanism/pom.xml, microprofile-fault-tolerance/README.adoc, microprofile-fault-tolerance/pom.xml, microprofile-openapi/pom.xml, pom.xml
JIRA's:
- https://issues.redhat.com/browse/WFLY-13271
- https://issues.redhat.com/browse/WFLY-13272
Upstream #403
=> [19.x] Upgrade wildfly-maven-plugin and fix WildFly version

microprofile-rest-client/country-client/pom.xml, microprofile-rest-client/country-server/pom.xml, microprofile-rest-client/pom.xml, pom.xml
https://issues.redhat.com/browse/WFLY-13450
=> WFLY-13450 Missing README.html for microprofile-rest-client QS

microprofile-health/README.adoc
https://issues.redhat.com/browse/WFLY-13458
=> WFLY-13458 Issues in readme for microprofile-health QS

microprofile-rest-client/README.adoc
https://issues.redhat.com/browse/WFLY-13465
=> WFLY-13465 Issues in readme for microprofile-rest-client QS

microprofile-metrics/README.adoc
https://issues.redhat.com/browse/WFLY-13463
=> WFLY-13463 Issues in readme for microprofile-metrics QS

microprofile-metrics/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13463
=> [WFLY-13463] syncs mp metrics pom.xml comments with README.adoc

microprofile-rest-client/country-client/pom.xml, microprofile-rest-client/country-server/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13465
=> [WFLY-13465] syncs mp rest-client pom.xml comments with README.adoc

microprofile-opentracing/pom.xml
https://issues.redhat.com/browse/WFLY-13467
=> [WFLY-13467] syncs mp opentracing pom.xml comments with README.adoc

microprofile-config/README.adoc, microprofile-fault-tolerance/README.adoc, microprofile-fault-tolerance/pom.xml, shared-doc/define-standalone-server-attributes.adoc
WFLY-13475 MP FT Quickstart: Change server startup documentation to reference local installation and standalone-microprofile.xml
=> WFLY-13475 MP FT Quickstart: Change server startup documentation to reference local installation and standalone-microprofile.xml

microprofile-config/README.adoc, microprofile-config/pom.xml, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/custom/CustomPropertiesFileProvider.java, microprofile-config/src/test/java/org/wildfly/quickstarts/microprofile/config/MicroProfileConfigIT.java, microprofile-health/README.adoc, shared-doc/run-arquillian-tests.adoc
https://issues.redhat.com/browse/WFLY-13462
=> WFLY-13462 Issues in readme for microprofile-config QS

microprofile-jwt/README.adoc
https://issues.redhat.com/browse/WFLY-13477
=> [WFLY-13477] Set the server type to 'microprofile' so the standalone-microprofile.xml is used.

microprofile-config/README.adoc, microprofile-fault-tolerance/README.adoc, microprofile-health/README.adoc, microprofile-jwt/README.adoc, microprofile-metrics/README.adoc, microprofile-opentracing/README.adoc, microprofile-rest-client/README.adoc, shared-doc/setup-repositories.adoc
https://issues.redhat.com/browse/WFLY-13473
=> WFLY-13473 Missing repositories in generated poms for MP QS in EAP

microprofile-fault-tolerance/README.adoc
Resolves
https://issues.redhat.com/browse/WFLY-13479
https://issues.redhat.com/browse/WFLY-13476
=>  WFLY-13476 MP FT QS: Missing supported shared-docs sections + WFLY-13479 MP FT QS: Corrections in English language README.md write-up

microprofile-openapi/README.adoc, microprofile-openapi/pom.xml
https://issues.redhat.com/browse/WFLY-13464
=> WFLY-13464 Change server startup documentation to reference local installation and standalone-microprofile.xml

microprofile-rest-client/README.adoc, microprofile-rest-client/pom.xml
https://issues.redhat.com/browse/WFLY-13450
=> WFLY-13450 Fix wrong wildfly-maven-plugin definition in rest-client

microprofile-health/README.adoc
https://issues.redhat.com/browse/WFLY-13496
=> WFLY-13496 Fix the jar reference in the microprofile-health QS

CONTRIBUTING.adoc, guide/Archetype.asciidoc, guide/GettingStarted.asciidoc, guide/GreeterQuickstart.asciidoc, guide/HelloworldQuickstart.asciidoc, guide/KitchensinkQuickstart.asciidoc, guide/NumberguessQuickstart.asciidoc, shared-doc/attributes.adoc, shared-doc/run-the-quickstart-in-jboss-developer-studio.adoc, shared-doc/system-requirements.adoc
Issue: https://issues.redhat.com/browse/WFLY-13718
=> [WFLY-13718] move to codeready studio

microprofile-rest-client/README.adoc
https://issues.redhat.com/browse/WFLY-13746
=> WFLY-13746 Issues in MP REST Client QS README

.github/workflows/ci.yml
Signed-off-by: Ken Wills <kwills@redhat.com>
=> Add github actions for quickstarts

guide/GreeterQuickstart.asciidoc
This simple formatting problem caused me a couple of hours of debugging/rouble shooting
=> <jta-data-source> tag cannot include line breaks

jaxrs-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13915
=> [WFLY-13915] adds commons logging to jaxrs client test dependencies

.github/workflows/ci.yml
Signed-off-by: Ken Wills <kwills@redhat.com>
=> test for CI

README.adoc, microprofile-config/README.adoc, microprofile-fault-tolerance/README.adoc, microprofile-fault-tolerance/pom.xml, microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/Coffee.java, microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeResource.java, microprofile-fault-tolerance/src/test/java/org/wildfly/quickstarts/microprofile/faulttolerance/MicroProfileFaultToleranceIT.java, microprofile-fault-tolerance/src/test/resources/arquillian.xml, microprofile-health/README.adoc, microprofile-health/src/test/java/org/wildfly/quickstarts/microprofile/health/MicroProfileHealthIT.java, microprofile-jwt/README.adoc, microprofile-metrics/README.adoc, microprofile-openapi/README.adoc, microprofile-opentracing/README.adoc, microprofile-rest-client/README.adoc, shared-doc/attributes.adoc, shared-doc/build-and-deploy-the-quickstart.adoc, shared-doc/start-the-standalone-server.adoc, shared-doc/xp-create-project.adoc, shared-doc/xp-deploy-project.adoc, shared-doc/xp-import-imagestreams-templates.adoc, shared-doc/xp-install-jaeger.adoc, shared-doc/xp-openshift-getting-started.adoc, shared-doc/xp-post-deployment-tasks.adoc
Issue: https://issues.redhat.com/browse/WFLY-13645
=> [WFLY-13645] Openshift S2i support for MicroProfile Quickstarts

microprofile-config/pom.xml, microprofile-fault-tolerance/pom.xml, microprofile-health/pom.xml, microprofile-jwt/pom.xml, microprofile-metrics/pom.xml, microprofile-openapi/pom.xml, microprofile-opentracing/pom.xml, microprofile-rest-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13982
=> Fix for WFLY-13982, Upgrade Bootable JAR Maven plugin to 2.0.1.Final

README.adoc
https://issues.redhat.com/browse/WFLY-14164
=> [WFLY-14164] fixed a typo in a directory name of the BOMs

pom.xml
Issue: https://issues.redhat.com/browse/WFLY-14173
=> [WFLY-14173] adds asciidoctor maven plugin to plugin management and update its version

shared-doc/attributes.adoc, shared-doc/xp-deploy-project.adoc, shared-doc/xp-import-imagestreams-templates.adoc, shared-doc/xp-post-deployment-tasks.adoc
Issue: https://issues.redhat.com/browse/WFLY-14228
=> [WFLY-14228] move to xp2 s2i images and templates

shared-doc/xp-deploy-project.adoc
Issue: https://issues.redhat.com/browse/WFLY-14239
=> [WFLY-14239] use latest xp images when creating new app

microprofile-jwt/README.adoc
Issue: https://issues.redhat.com/browse/WFLY-14360
=> WFLY-14360 Fix typo in README of MP-JWT Quickstart

microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/custom/CustomConfigSource.java, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/custom/CustomPropertiesFileProvider.java
https://issues.redhat.com/browse/WFLY-14201
https://issues.redhat.com/browse/WFLY-14398
=> [WFLY-14201][WFLY-14398] MP Config 2.0 changes

microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/custom/CustomConfigSource.java, microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/custom/CustomPropertiesFileProvider.java
https://issues.redhat.com/browse/WFLY-14201
https://issues.redhat.com/browse/WFLY-14398
=> [WFLY-14201][WFLY-14398] Update for MP Config 2.0

microprofile-config/pom.xml, microprofile-fault-tolerance/pom.xml, microprofile-health/pom.xml, microprofile-jwt/pom.xml, microprofile-metrics/pom.xml, microprofile-openapi/pom.xml, microprofile-opentracing/pom.xml, microprofile-rest-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-14491
=> Fix for WFLY-14491, Upgrade to Bootable JAR 4.0.0.Beta1

ejb-txn-remote-call/client/client-cr.yaml, ejb-txn-remote-call/client/pom.xml, ejb-txn-remote-call/server/pom.xml, ejb-txn-remote-call/server/server-cr.yaml
upstream PR: https://github.com/wildfly/quickstart/pull/478
https://issues.redhat.com/browse/WFLY-12904
=> [WFLY-12904] s2i build fix for quickstart ejb-txn-remote-call

ejb-txn-remote-call/README.adoc, ejb-txn-remote-call/client/extensions/postgresql.deployment.yaml
https://issues.redhat.com/browse/WFLY-12904
master PR: https://github.com/wildfly/quickstart/pull/480
=> [WFLY-12904] adding ifndef for WFLY and EAP, parametrize ejb-txn-remote-call README.adoc with product version

helloworld-classfiletransformer/README.adoc, helloworld-classfiletransformer/pom.xml, helloworld-classfiletransformer/src/main/java/hello/client/HelloClient.java, helloworld-classfiletransformer/src/main/java/hello/server/transformation/HelloByteCodeManipulator.java
Issue: https://issues.redhat.com/browse/WFLY-11794
=> [WFLY-11794] Fixing helloworld class file transformer quickstart example

microprofile-reactive-messaging-kafka/src/test/java/org/wildfly/quickstarts/microprofile/reactive/messaging/test/RunKafkaSetupTask.java
https://issues.redhat.com/browse/WFLY-14651
=> [WFLY-14651] Pre create topic to avoid LEADER_NOT_AVAILABLE

microprofile-reactive-messaging-kafka/src/test/java/org/wildfly/quickstarts/microprofile/reactive/messaging/test/RunKafkaSetupTask.java
Upstream: https://github.com/wildfly/quickstart/pull/490
https://issues.redhat.com/browse/WFLY-14651
=> [23.x][WFLY-14651] Pre create topic to avoid LEADER_NOT_AVAILABLE

microprofile-config/pom.xml, microprofile-fault-tolerance/pom.xml, microprofile-health/pom.xml, microprofile-jwt/pom.xml, microprofile-metrics/pom.xml, microprofile-openapi/pom.xml, microprofile-opentracing/pom.xml, microprofile-reactive-messaging-kafka/pom.xml, microprofile-rest-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-14700
=> [23.x] Fix for WFLY-14700, Upgrade quickstarts to Bootable JAR 4.0.3.Final

pom.xml, spring-greeter/pom.xml, spring-kitchensink-basic/README.adoc, spring-kitchensink-basic/pom.xml, spring-kitchensink-basic/src/main/webapp/WEB-INF/views/index.jsp, spring-kitchensink-springmvctest/README.adoc, spring-kitchensink-springmvctest/pom.xml, spring-kitchensink-springmvctest/src/main/webapp/WEB-INF/views/index.jsp, spring-resteasy/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-11058
=> WFLY-11058: updates quickstarts for spring 5

microprofile-config/pom.xml, microprofile-fault-tolerance/pom.xml, microprofile-health/pom.xml, microprofile-jwt/pom.xml, microprofile-metrics/pom.xml, microprofile-openapi/pom.xml, microprofile-opentracing/pom.xml, microprofile-reactive-messaging-kafka/pom.xml, microprofile-rest-client/pom.xml, todo-backend/pom.xml
In addition, I am evolving wildfly-datasources-galleon-pack version.
=> Fix for WFLY-14176, Upgrade quickstarts to use Bootable JAR plugin 5.0.0.Beta1

shared-doc/attributes.adoc, todo-backend/README.adoc
* Updated documentation to be able to generate documentation for EAP XP.
JIRA: https://issues.redhat.com/browse/WFLY-14563
=> [WFLY-14563] todo-backend quickstart

shared-doc/attributes.adoc, todo-backend/README.adoc
* Updated documentation to be able to generate documentation for EAP XP.
JIRA: https://issues.redhat.com/browse/WFLY-14563
=> [23.x] [WFLY-14563] todo-backend quickstart

todo-backend/pom.xml
https://issues.redhat.com/browse/WFLY-15063
=> WFLY-15063 Upgrade wildfly-datasources-galleon-pack dependency to 2.0.3.Final

microprofile-config/pom.xml, microprofile-fault-tolerance/pom.xml, microprofile-health/pom.xml, microprofile-jwt/pom.xml, microprofile-metrics/pom.xml, microprofile-openapi/pom.xml, microprofile-opentracing/pom.xml, microprofile-reactive-messaging-kafka/pom.xml, microprofile-rest-client/pom.xml, todo-backend/pom.xml
https://issues.redhat.com/browse/WFLY-15065
=> [WFLY-15065] Upgrade quickstarts to use Bootable JAR plugin 5.0.2.Final

todo-backend/README.adoc
Fix Helm Chart instructions for todo-backend
JIRA: https://issues.redhat.com/browse/WFLY-15069
=> [WFLY-15069] Fix Helm Chart instructions for todo-backend

pom.xml
Issue: https://issues.redhat.com/browse/WFLY-15290
=> [WFLY-15290] remove drupal profiles from parent

bean-validation-custom-constraint/pom.xml, bean-validation/pom.xml, contacts-jquerymobile/pom.xml, ejb-in-war/pom.xml, helloworld-mbean/pom.xml, helloworld-ws/pom.xml, kitchensink-angularjs/pom.xml, kitchensink-ear/pom.xml, kitchensink-jsp/pom.xml, kitchensink-ml/pom.xml, kitchensink/pom.xml, managed-executor-service/pom.xml, microprofile-config/pom.xml, microprofile-fault-tolerance/pom.xml, microprofile-health/pom.xml, microprofile-jwt/pom.xml, microprofile-metrics/pom.xml, microprofile-opentracing/pom.xml, microprofile-reactive-messaging-kafka/pom.xml, microprofile-rest-client/pom.xml, spring-resteasy/pom.xml, tasks-jsf/pom.xml, tasks-rs/pom.xml, todo-backend/pom.xml, wsat-simple/pom.xml, wsba-coordinator-completion-simple/pom.xml, wsba-participant-completion-simple/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-15323
=> [WFLY-15323] add missing arquillian profiles

microprofile-health/README.adoc
https://issues.redhat.com/browse/WFLY-15089
=> [WFLY-15089] Add startup health checks to microprofile-health quickstart

dist/src/main/assembly/assembly.xml, microprofile-fault-tolerance/pom.xml, microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeResource.java, pom.xml
Issue: https://issues.redhat.com/browse/WFLY-15381
=> [WFLY-15381] fix microprofile-faul-tolerance quickstart

ee-security/configure-elytron.cli, ee-security/restore-configuration.cli
https://issues.redhat.com/browse/WFLY-15671
=> [WFLY-15671] Update the CLI scripts to reflect the present default configuration.

jaxrs-client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-15643
=> [WFLY-15643] adds arquillian profiles to jaxrs-client quickstarts

microprofile-reactive-messaging-kafka/README.adoc, microprofile-reactive-messaging-kafka/xp-install-rhosak.adoc, shared-doc/build-and-run-the-quickstart-with-bootable-jar.adoc
https://issues.redhat.com/browse/WFLY-15772
=> [WFLY-15772] RHOSAK now requires ACLs

microprofile-reactive-messaging-kafka/README.adoc
https://issues.redhat.com/browse/WFLY-16071
Upstream: #550
=> [WFLY-16071] Set standalone-server-type to 'microprofile'

microprofile-reactive-messaging-kafka/pom.xml
This removes the need to downgrade Kafka.
https://issues.redhat.com/browse/WFLY-16074
=> [WFLY-16074] Upgrade to upstream spring kafka

microprofile-reactive-messaging-kafka/README.adoc, microprofile-reactive-messaging-kafka/helm-amq-streams.yml, microprofile-reactive-messaging-kafka/helm-rhosak.yml, shared-doc/attributes.adoc, shared-doc/build-and-run-the-quickstart-with-bootable-jar.adoc
https://issues.redhat.com/browse/WFLY-16103
https://issues.redhat.com/browse/WFLY-16104
=> [WFLY-16103][WFLY-16104]  MicroProfile RM QS Helm chart fixes

microprofile-reactive-messaging-kafka/README.adoc, microprofile-reactive-messaging-kafka/helm-amq-streams.yml, microprofile-reactive-messaging-kafka/helm-rhosak.yml, microprofile-reactive-messaging-kafka/pom.xml, microprofile-reactive-messaging-kafka/src/main/jkube/route.yml, shared-doc/attributes.adoc, shared-doc/build-and-run-the-quickstart-with-bootable-jar.adoc
First two commits:
https://github.com/wildfly/quickstart/pull/545
Last commits:
https://github.com/wildfly/quickstart/pull/554 / https://issues.redhat.com/browse/WFLY-16103 + https://issues.redhat.com/browse/WFLY-16104
=> 26.x backports for Reactive Messaging

ha-singleton-service/README.adoc
Resolves
https://issues.redhat.com/browse/WFLY-16351
=> WFLY-16351 Conscious Language in ha-singleton-service quickstart

batch-processing/src/main/java/org/jboss/as/quickstarts/batch/controller/BatchController.java, batch-processing/src/main/java/org/jboss/as/quickstarts/batch/util/Resources.java, batch-processing/src/main/webapp/WEB-INF/faces-config.xml, cmt/src/main/java/org/jboss/as/quickstarts/cmt/controller/CustomerManager.java, cmt/src/main/resources/META-INF/persistence.xml, cmt/src/main/webapp/WEB-INF/faces-config.xml, cmt/src/main/webapp/addCustomer.xhtml, ejb-multi-server/app-main/web/src/main/webapp/WEB-INF/faces-config.xml, helloworld-singleton/src/main/webapp/WEB-INF/faces-config.xml, hibernate/src/main/java/org/jboss/as/quickstart/hibernate/util/Resources.java, hibernate/src/main/webapp/WEB-INF/faces-config.xml, jsonp/src/main/webapp/WEB-INF/faces-config.xml, jts/application-component-1/src/main/webapp/WEB-INF/faces-config.xml, kitchensink/src/main/java/org/jboss/as/quickstarts/kitchensink/util/Resources.java, kitchensink/src/main/resources/META-INF/persistence.xml, kitchensink/src/main/webapp/WEB-INF/faces-config.xml, mail/src/main/webapp/WEB-INF/faces-config.xml, numberguess/src/main/webapp/WEB-INF/faces-config.xml, tasks-jsf/src/main/java/org/jboss/as/quickstarts/tasksJsf/AuthController.java, tasks-jsf/src/main/java/org/jboss/as/quickstarts/tasksJsf/TaskController.java, tasks-jsf/src/main/resources/META-INF/persistence.xml, tasks-jsf/src/main/webapp/WEB-INF/faces-config.xml, tasks-jsf/src/main/webapp/index.xhtml, tasks-jsf/src/main/webapp/tasks.xhtml, temperature-converter/src/main/webapp/WEB-INF/faces-config.xml
https://issues.redhat.com/browse/WFLY-16839
Update faces-config.xml to latest schema version
Update persistence.xml in related projects
Modify EL value handling WRT CDI managed beans
Remove CDI @Produces methods for FacesContext, as that's a spec function now
=> [WFLY-16839] Faces-related fixes

todo-backend/src/main/java/org/wildfly/quickstarts/todos/ToDoDAOImpl.java
https://issues.redhat.com/browse/WFLY-17185
=> WFLY-17185 todo-backend QS fires a StrictJpaComplianceViolation exception

microprofile-reactive-messaging-kafka/pom.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17193
https://issues.redhat.com/browse/WFLY-17187
=> [WFLY-17193] [WFLY-17187] Verify mp-config and mp-reactive-messaging with jakarta 

microprofile-openapi/README.adoc, pom.xml
https://issues.redhat.com/browse/WFLY-17191
=> WFLY-17191 Verify and enable the the microprofile-openapi quickstart

bean-validation-custom-constraint/src/test/resources/arquillian.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17205
Enable module
Update outdated arquillian config
=> [WFLY-17205] Verify and enable the the bean-validation-custom-constraint quickstart

ee-security/README.adoc, ee-security/src/main/java/org/jboss/as/quickstarts/ee_security/ElytronIdentityStore.java
https://issues.redhat.com/browse/WFLY-17201
=> [WFLY-17201] Update the EE Security quickstart to contain the identities in the identity store.

microprofile-rest-client/country-client/pom.xml, microprofile-rest-client/country-server/pom.xml, microprofile-rest-client/pom.xml, pom.xml
Signed-off-by: James R. Perkins <jperkins@redhat.com>
=> [WFLY-17192] Enable the microprofile-rest-client quickstart.

kitchensink/pom.xml, kitchensink/src/test/java/org/jboss/as/quickstarts/kitchensink/test/RemoteMemberRegistrationIT.java
=> Adding remote test for Kitchensink

cmt/pom.xml, ee-security/pom.xml, helloworld-mdb/pom.xml, helloworld-ws/pom.xml, jaxrs-client/pom.xml, kitchensink/pom.xml, numberguess/pom.xml, servlet-security/pom.xml, shared-doc/attributes.adoc, temperature-converter/pom.xml, thread-racing/pom.xml, websocket-hello/pom.xml
=> Fixing typo on profile name

jaxrs-client/src/test/java/org/jboss/as/quickstarts/jaxrsclient/test/ProvisionedManagedContactRestClientIT.java, servlet-security/pom.xml, servlet-security/src/main/java/org/jboss/as/quickstarts/servlet_security/SecuredServlet.java, servlet-security/src/test/java/org/jboss/as/quickstarts/servlet_security/ProvisionedManagedSecureIT.java, servlet-security/src/test/java/org/jboss/as/quickstarts/servlet_security/RemoteSecureIT.java, todo-backend/README.adoc, todo-backend/src/test/java/org/wildfly/quickstarts/todos/RemoteToDoIT.java
Fixing todo-backend and jaxrs-client small issues
=> Adding test for servlet-security

cmt/charts/helm.yaml, ee-security/charts/helm.yaml, ee-security/configure-elytron.cli, ee-security/pom.xml, ee-security/src/test/java/org/jboss/as/quickstarts/ee_security/ProvisionedManagedSecureIT.java, ee-security/src/test/java/org/jboss/as/quickstarts/ee_security/RemoteSecureIT.java, helloworld-ws/charts/helm.yaml, helloworld/charts/helm.yaml, jaxrs-client/charts/helm.yaml, kitchensink/charts/helm.yaml, servlet-security/charts/helm.yaml, temperature-converter/charts/helm.yaml, thread-racing/charts/helm.yaml, todo-backend/todo-backend-chart/values.yaml, websocket-hello/charts/helm.yaml
=> Adding tests to ee-security

ee-security/configure-elytron.cli
=> Commenting the reload operation as it freezes the build on OpenShift

.gitignore, cmt/charts/helm.yaml, helloworld-mdb/charts/helm.yaml, websocket-hello/pom.xml, websocket-hello/src/test/java/org/jboss/as/quickstarts/websocket_hello/EchoListener.java, websocket-hello/src/test/java/org/jboss/as/quickstarts/websocket_hello/ProvisionedManagedWebsocketIT.java, websocket-hello/src/test/java/org/jboss/as/quickstarts/websocket_hello/RemoteWebSocketIT.java, websocket-hello/src/test/resources/arquillian.xml
=> Adding tests to cover websocket-hello

numberguess/pom.xml, numberguess/src/test/java/org/jboss/as/quickstarts/numberguess/ProvisionedManagedNumberGuessIT.java, numberguess/src/test/java/org/jboss/as/quickstarts/numberguess/RemoteNumberGuessIT.java
=> Adding simple integration testfor NumberGuess

temperature-converter/pom.xml, temperature-converter/src/test/java/org/jboss/as/quickstarts/temperatureconverter/ProvisionedManagedTemperatureConverterIT.java, temperature-converter/src/test/java/org/jboss/as/quickstarts/temperatureconverter/RemoteTemperatureConverterIT.java
=> Adding tests covering temperatuer-converter

thread-racing/pom.xml, thread-racing/src/test/java/org/jboss/as/quickstarts/threadracing/EchoListener.java, thread-racing/src/test/java/org/jboss/as/quickstarts/threadracing/ProvisionedManagedThreadRacingIT.java, thread-racing/src/test/java/org/jboss/as/quickstarts/threadracing/RemoteThreadRacingIT.java, thread-racing/src/test/resources/arquillian.xml, websocket-hello/pom.xml, websocket-hello/src/test/java/org/jboss/as/quickstarts/websocket_hello/RemoteWebSocketIT.java
=> Adding tests to cover thread-racing

jaxrs-client/pom.xml, jaxrs-client/src/test/java/org/jboss/as/quickstarts/jaxrsclient/test/ProvisionedManagedContactRestClientIT.java
=> Fixing typo in test name

cmt/pom.xml, cmt/src/test/java/org/jboss/as/quickstarts/cmt/ProvisionedManagedCustomerIT.java, cmt/src/test/java/org/jboss/as/quickstarts/cmt/RemoteCustomerIT.java
=> Adding tests covering cmt quickstart

shared-doc/run-arquillian-functional-tests-remote.adoc, todo-backend/README.adoc
=> Updating the doc to have bootable jar working on Openshift

dist/src/main/assembly/assembly.xml, helloworld-mdb/install-domain.cli, helloworld-mdb/pom.xml, helloworld-mdb/remove-domain.cli, helloworld-mdb/src/main/webapp/WEB-INF/beans.xml, pom.xml
Issue: https://issues.redhat.com/browse/WFLY-17400
=> [WFLY-17400] Verify and re-enable helloworld-mdb quickstart

dist/src/main/assembly/assembly.xml, mail/configure-mail-session.cli, mail/src/main/webapp/WEB-INF/beans.xml, mail/src/main/webapp/WEB-INF/faces-config.xml, mail/src/main/webapp/home.xhtml, pom.xml
Jira issue: https://issues.redhat.com/browse/WFLY-17447
- Re-enable the quickstart 
- Enable debug traces because there is no good feedback about what is happening behind the scenes
- Use Jakarta EE 10 schemas
- Minor formatting for home.xhtml
=> [WFLY-17447] Re-enable Mail Quickstart

batch-processing/pom.xml, batch-processing/src/main/java/org/jboss/as/quickstarts/batch/controller/BatchController.java, batch-processing/src/main/resources/META-INF/batch-jobs/import-file.xml, batch-processing/src/main/resources/META-INF/persistence.xml, batch-processing/src/main/webapp/WEB-INF/beans.xml, batch-processing/src/main/webapp/WEB-INF/faces-config.xml, dist/src/main/assembly/assembly.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17396
=> WFLY-17396 Verify and re-enable batch-processing quickstart

dist/src/main/assembly/assembly.xml, pom.xml, shopping-cart/client/pom.xml
https://issues.redhat.com/browse/WFLY-17403
=> WFLY-17403 Verify and re-enable shopping-cart quickstart

dist/src/main/assembly/assembly.xml, ejb-throws-exception/ejb/src/main/resources/META-INF/beans.xml, ejb-throws-exception/web/src/main/webapp/WEB-INF/beans.xml, ejb-throws-exception/web/src/main/webapp/WEB-INF/faces-config.xml, ejb-throws-exception/web/src/main/webapp/WEB-INF/web.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17398
=> WFLY-17398 Verify and re-enable ejb-throws-exception quickstart

dist/src/main/assembly/assembly.xml, helloworld-singleton/src/main/webapp/WEB-INF/beans.xml, helloworld-singleton/src/main/webapp/WEB-INF/faces-config.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17401
=> WFLY-17401 Verify and re-enable helloworld-singleton quickstart

dist/src/main/assembly/assembly.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17402
=> WFLY-17402 Verify and re-enable ejb-remote quickstart

dist/src/main/assembly/assembly.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17390
=> WFLY-17390 Re-enable ejb-timer quickstart

dist/src/main/assembly/assembly.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17391
https://issues.redhat.com/browse/WFLY-17392
=> WFLY-17391, WFLY-17392 Re-enable ha-singleton-deployment and ha-singleton-service quickstarts

dist/src/main/assembly/assembly.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17485
This PR depends on https://github.com/wildfly/quickstart/pull/573 being merged first.
=> [WFLY-17485] Verify and re-enable http-custom-mechanism quickstart

helloworld-mutual-ssl-secured/README.adoc
https://issues.redhat.com/browse/WFLY-17448
=> [WFLY-17448] Update helloworld-mutual-ssl-secured quickstart README

ejb-multi-server/app-main/ear/src/main/application/META-INF/jboss-ejb-client.xml, ejb-multi-server/app-web/src/main/webapp/META-INF/jboss-ejb-client.xml, ejb-multi-server/install-domain.cli
https://issues.redhat.com/browse/WFLY-16857
=> [WFLY-16857] Migrate ejb-multi-server quickstart from legacy security to elytron

guide/GettingStarted.asciidoc
Fixes https://issues.redhat.com/browse/WFLY-17466
here: asciidoctor: WARN: ...main/guide/GettingStarted.asciidoc: line 136: unterminated listing block
=> [WFLY-17466] Various AsciiDoc issues

dist/src/main/assembly/assembly.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17481
https://issues.redhat.com/browse/WFLY-17482
https://issues.redhat.com/browse/WFLY-17483
=> [WFLY-17481][WFLY-17482][WFLY-17483] Re-enabling servlet-async , servlet-filterlistener and websocket-endpoint quickstarts

dist/src/main/assembly/assembly.xml, ejb-multi-server/README.adoc, ejb-multi-server/app-main/ejb/src/main/resources/META-INF/ejb-jar.xml, ejb-multi-server/app-main/web/src/main/webapp/WEB-INF/beans.xml, ejb-multi-server/app-main/web/src/main/webapp/WEB-INF/faces-config.xml, ejb-multi-server/client/pom.xml, ejb-multi-server/install-domain.cli, ejb-multi-server/pom.xml, pom.xml
https://issues.redhat.com/browse/WFLY-17397
=> WFLY-17397 Verify and re-enable ejb-multi-server quickstart

dist/src/main/assembly/assembly.xml, hibernate/README.adoc, hibernate/src/main/java/org/jboss/as/quickstart/hibernate/data/MemberListProducer.java, hibernate/src/main/java/org/jboss/as/quickstart/hibernate/model/Member.java, hibernate/src/main/java/org/jboss/as/quickstart/hibernate/service/MemberRegistration.java, hibernate/src/main/java/org/jboss/as/quickstart/hibernate/util/Resources.java, pom.xml
https://issues.redhat.com/browse/WFLY-17527
=> WFLY-17527 Verify and re-enable Hibernate quickstart

dist/src/main/assembly/assembly.xml, microprofile-fault-tolerance/README.adoc, microprofile-fault-tolerance/pom.xml, microprofile-fault-tolerance/src/test/resources/arquillian.xml, pom.xml
Resolves
https://issues.redhat.com/browse/WFLY-17542
https://issues.redhat.com/browse/WFLY-17546
+ minor fixes
=> WFLY-17542 Verify and re-enable microprofile-fault-tolerance quickstart

dist/src/main/assembly/assembly.xml, messaging-clustering-singleton/src/main/webapp/WEB-INF/beans.xml, pom.xml
* Updating the XM to JakartaEE 10
* Re-enabling the messaging-clustering-singleton quickstart
Jira: https://issues.redhat.com/browse/WFLY-17538
=> [WFLY-17538]: Verify and re-enable messaging-clustering-singleton quickstart.

dist/src/main/assembly/assembly.xml
Issue: https://issues.redhat.com/browse/WFLY-17528
=> [WFLY-17528] enable jaxws-ejb in assembly.xml

dist/src/main/assembly/assembly.xml, pom.xml
Issue: https://issues.redhat.com/browse/WFLY-17529
=> [WFLY-17529] enable jaxws-retail in parent structure

helloworld-ws/pom.xml, jaxrs-client/pom.xml, kitchensink/pom.xml, todo-backend/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-17823
=> [WFLY-17823] removed unsed arq-managed testing profiles

shared-doc/attributes.adoc
Issue: https://issues.redhat.com/browse/WFLY-17950
=> [WFLY-17950] update shared-docs attributes

shared-doc/attributes.adoc
Issue: https://issues.redhat.com/browse/WFLY-17950
=> [28.x][WFLY-17950] update shared-docs attributes

README.adoc, todo-backend/README.adoc
Issue: https://issues.redhat.com/browse/WFLY-18046
=> [WFLY-18046] minor root README fixes

helloworld-ws/pom.xml
https://issues.redhat.com/browse/WFLY-18078
=> [WFLY-18078] helloworld-ws dependencies should be provided

http-custom-mechanism/custom-module/pom.xml, http-custom-mechanism/webapp/pom.xml
https://issues.redhat.com/browse/WFLY-18077
=> [WFLY-18077] Make the http-custom-mechanism dependencies provided

guide/GettingStarted.asciidoc
Issue: https://issues.redhat.com/browse/WFLY-17704
=> WFLY-17704 Broken formatting in the Getting Started Developing Applications Guide

cmt/pom.xml, ee-security/pom.xml, helloworld-mdb/pom.xml, helloworld-ws/pom.xml, helloworld/pom.xml, jaxrs-client/pom.xml, kitchensink/pom.xml, microprofile-config/pom.xml, microprofile-fault-tolerance/pom.xml, microprofile-health/pom.xml, microprofile-jwt/pom.xml, microprofile-openapi/pom.xml, microprofile-reactive-messaging-kafka/pom.xml, microprofile-rest-client/pom.xml, numberguess/pom.xml, remote-helloworld-mdb/pom.xml, servlet-security/pom.xml, temperature-converter/pom.xml, thread-racing/pom.xml, todo-backend/pom.xml, websocket-hello/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-18271
=> Fix for WFLY-18271, Upgrade provisioning artifacts for WildFly 29.0.0.Final

.github/workflows/quickstart_microprofile-openapi_ci.yml, microprofile-openapi/README.adoc, microprofile-openapi/charts/helm.yaml, microprofile-openapi/pom.xml, microprofile-openapi/src/main/jkube/route.yml, microprofile-openapi/src/test/java/org/wildfly/quickstarts/microprofile/openapi/BasicRuntimeIT.java
Issue: https://issues.redhat.com/browse/WFLY-18497
=> [WFLY-18497] microprofile-openapi Quickstart CY2023Q3 enhancements

shared-doc/helm-deploy-project.adoc
https://issues.redhat.com/browse/WFLY-18553
=> [WFLY-18553] Replace the manual waiting with --wait

.github/workflows/project_ci.yml, .github/workflows/quickstart_ci.yml, .github/workflows/quickstart_helloworld_ci.yml, .github/workflows/quickstart_microprofile-config_ci.yml, .github/workflows/quickstart_microprofile-openapi_ci.yml, .github/workflows/quickstart_thread-racing_ci.yml, cmt/pom.xml, contacts-jquerymobile/pom.xml, helloworld-ws/pom.xml, microprofile-config/pom.xml, remote-helloworld-mdb/pom.xml, spring-resteasy/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-18526
=> [WFLY-18526] updates CI jobs wrt BOMs move to Server's repo

microprofile-openapi/pom.xml
https://issues.redhat.com/browse/WFLY-18497
=> [WFLY-18497] Reduce layers for MP OpenApi

microprofile-config/pom.xml
https://issues.redhat.com/browse/WFLY-18493
=> [WFLY-18493] Reduce layers needed for MP Config

CODE_OF_CONDUCT.adoc, SECURITY.adoc
Issue: https://issues.redhat.com/browse/WFLY-18221
=> [WFLY-18221] added code of conduct and security adocs

.github/workflows/quickstart_microprofile-jwt_ci.yml, microprofile-jwt/README.adoc, microprofile-jwt/charts/helm.yaml, microprofile-jwt/pom.xml, microprofile-jwt/src/test/java/org/wildfly/quickstarts/mpjwt/BasicRuntimeIT.java, microprofile-jwt/src/test/java/org/wildfly/quickstarts/mpjwt/JWTClientIT.java, microprofile-jwt/src/test/java/org/wildfly/quickstarts/mpjwt/TestUtils.java
https://issues.redhat.com/browse/WFLY-18496
=> [WFLY-18496[ microprofile-jwt Quickstart CY2023Q3 enhancements

microprofile-jwt/pom.xml
https://issues.redhat.com/browse/WFLY-18496
=> [WFLY-18496] Set the artifact id as in the other quickstarts

.github/workflows/quickstart_helloworld-mdb_ci.yml, helloworld-mdb/README.adoc, helloworld-mdb/pom.xml, helloworld-mdb/src/main/java/org/jboss/as/quickstarts/servlet/HelloWorldMDBServletClient.java, helloworld-mdb/src/test/java/org/wildfly/quickstarts/mdb/BasicRuntimeIT.java
* Updating the docs
* Adding an integration test
* Updating the pom
=> WFLY-18474: helloworld-mdb Quickstart Common Enhancements CY2023Q3

.github/workflows/quickstart_batch-processing_ci.yml, batch-processing/README.adoc, batch-processing/charts/helm.yaml, batch-processing/pom.xml, batch-processing/src/test/java/org/wildfly/quickstarts/batch/BasicRuntimeIT.java, helloworld/pom.xml, shared-doc/run-integration-tests-with-openshift.adoc
Issue: https://issues.redhat.com/browse/WFLY-18458
=> [WFLY-18458] batch-processing quickstart enhancement CY2023Q3

thread-racing/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-18511
=> [WFLY-18511] fixes provisioned-server config and integration-testing

.github/workflows/quickstart_jta-crash-rec_ci.yml, jta-crash-rec/pom.xml, jta-crash-rec/src/test/java/org/jboss/as/quickstarts/xa/BasicRuntimeIT.java
Issue [WFLY-18487](https://issues.redhat.com/browse/WFLY-18487)
=> [WFLY-18487] jta-crash-rec Quickstart CY2023Q3 enhancements

.github/workflows/quickstart_microprofile-reactive-messaging-kafka_ci.yml
https://issues.redhat.com/browse/WFLY-18498
=> [WFLY-18498] Remove temp code

.github/workflows/quickstart_ci.yml
Issue: https://issues.redhat.com/browse/WFLY-18712
=> [WFLY-18712] adds CI support for non root deployment dir

.github/workflows/quickstart_servlet-async_ci.yml, servlet-async/README.adoc, servlet-async/charts/helm.yaml, servlet-async/pom.xml, servlet-async/src/test/java/org/jboss/as/quickstarts/servlet/async/BasicRuntimeIT.java
Issue: https://issues.redhat.com/browse/WFLY-18504
=> [WFLY-18504] servlet-async quickstart enhancement CY2023Q3

.github/workflows/quickstart_servlet-filterlistener_ci.yml, servlet-filterlistener/README.adoc, servlet-filterlistener/charts/helm.yaml, servlet-filterlistener/pom.xml, servlet-filterlistener/src/test/java/org/jboss/as/quickstarts/servlet/filterlistener/BasicRuntimeIT.java, servlet-filterlistener/src/test/java/org/jboss/as/quickstarts/servlet/filterlistener/FilterServletIT.java
Issue: https://issues.redhat.com/browse/WFLY-18505
=> [WFLY-18505] servlet-filterlistener quickstart enhancement CY2023Q3

servlet-async/pom.xml, websocket-endpoint/pom.xml, websocket-hello/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-18853
=> [WFLY-18853] added pluginManagement section for wildfly-maven-plugin

.github/workflows/quickstart_helloworld-singleton_ci.yml, helloworld-singleton/README.adoc, helloworld-singleton/charts/helm.yaml, helloworld-singleton/pom.xml, helloworld-singleton/src/test/java/org/jboss/as/quickstarts/singleton/BasicRuntimeIT.java
Issue: https://issues.redhat.com/browse/WFLY-18477
=> [WFLY-18477] helloworld-singleton quickstart enhancement CY2023Q3

.github/workflows/quickstart_ejb-throws-exception_ci.yml, ejb-throws-exception/README.adoc, ejb-throws-exception/ear/pom.xml, ejb-throws-exception/pom.xml, ejb-throws-exception/web/src/main/webapp/index.html, ejb-throws-exception/web/src/main/webapp/index.xhtml, ejb-throws-exception/web/src/test/java/org/jboss/as/quickstarts/ear/controller/BasicRuntimeIT.java
https://issues.redhat.com/browse/WFLY-18468
=> [WFLY-18468] further enhance ejb-throws-exception

shared-doc/helm-deploy-project.adoc, todo-backend/README.adoc, todo-backend/charts/Chart.yaml, todo-backend/helm-install-prerequisites.adoc
* Reusing the shared docs instead of duplicating the content.
* Adding the additional pre-requisites in a separate file.
Issue: https://issues.redhat.com/browse/WFLY-18887
=> [WFLY-18887]: Improving todo-backend documentation

dist/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-18956
Branch: main
=> [main] [WFLY-18956] Adds sha1 digest to dist module's zip files

mail/pom.xml
Jira issue: https://issues.redhat.com/browse/WFLY-18959
=> [WFLY-18959] Fix Mail quickstart dependencies scope

micrometer/pom.xml, opentelemetry-tracing/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-19015
=> [WFLY-19015] Replaces usage of non-user expansion BOM, with MP BOM

microprofile-health/pom.xml
Add goal verify into the integrations testing profile in MPHealth QS
=> [WFLY-19083] add goal verify into the integrations testing profile in MPHealth QS

CODEOWNERS
Jira: https://issues.redhat.com/browse/WFLY-19186
=> [WFLY-19186] Add CODEOWNERS

microprofile-jwt/pom.xml, microprofile-jwt/src/test/java/org/wildfly/quickstarts/mpjwt/JWTClientIT.java
https://issues.redhat.com/browse/WFLY-19228
=> WFLY-19228 JWTClientIT does not use Arquillian

ejb-txn-remote-call/client/pom.xml
https://issues.redhat.com/browse/WFLY-19614
=> [WFLY-19614] set current folder

spring-resteasy/src/test/java/org/jboss/as/quickstarts/resteasyspring/test/ResteasySpringIT.java
https://issues.redhat.com/browse/WFLY-19826
=> [WFLY-19826] add "/" to the URL

jta-crash-rec/src/test/java/org/jboss/as/quickstarts/xa/BasicRuntimeIT.java
https://issues.redhat.com/browse/WFLY-19828
=> [WFLY-19828] update default URL fro jta-crash-rec

logging/README.adoc
https://issues.redhat.com/browse/WFLY-19830
=> [WFLY-19830] update start configuration command for logging QS

ejb-txn-remote-call/README-source.adoc, ejb-txn-remote-call/client/pom.xml, ejb-txn-remote-call/client/scripts/remoting-configuration.cli, ejb-txn-remote-call/server/scripts/cli.local.properties
[WFLY-19913](https://issues.redhat.com/browse/WFLY-19913)
=> [WFLY-19913] Requested modifications have been implemented

.github/workflows/scripts/kubernetes/core/run-quickstart-test-on-kubernetes.sh
[WFLY-20210](https://issues.redhat.com/browse/WFLY-20210)
=> [WFLY-20210] Removed '/' from the qs_dir variable

ejb-remote/README-source.adoc, ejb-remote/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-19958
=> [WFLY-19958] Removes unproper OS support from ejb-remote

micrometer/charts/opentelemetry-collector-kubernetes.yaml, micrometer/charts/opentelemetry-collector-openshift.yaml, micrometer/docker-compose.yaml, micrometer/otel-collector-config.yaml, opentelemetry-tracing/charts/opentelemetry-collector-kubernetes.yaml, opentelemetry-tracing/charts/opentelemetry-collector-openshift.yaml, opentelemetry-tracing/configure-opentelemetry.cli, opentelemetry-tracing/otel-collector-config.yaml
https://issues.redhat.com/browse/WFLY-19535
- Update OpenTelemetry Collector image version
- Modify receiver configs to reflect collector changes 
- Modify exporter configs to reflect collector changes 
- Modify opentelemetry WildFly config to prevent unwanted span drops 
- Add opentelemetry metrics and log configs to prevent unwanted server log errors
=> [WFLY-19535] Sync WildFly and Quickstarts version of Otel Collector

microprofile-health/expose-management-port.adoc, shared-doc/build-and-run-the-quickstart-with-bootable-jar.adoc
Issue: https://issues.redhat.com/browse/WFLY-19925
=> [WFLY-19925] Fix microprofile-health README issues

mail/pom.xml, temperature-converter/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-20429
=> [WFLY-20429] Remove maven-compiler-plugin config

ejb-multi-server/install-domain.cli
https://issues.redhat.com/browse/WFLY-19841
=> [WFLY-19841] Fix multiserver io subsystem configuration

batch-processing/src/test/java/org/wildfly/quickstarts/batch/BasicRuntimeIT.java, cmt/src/test/java/org/wildfly/quickstarts/cmt/BasicRuntimeIT.java, ee-security/src/test/java/org/jboss/as/quickstarts/ee_security/BasicRuntimeIT.java, ejb-multi-server/app-web/src/test/java/org/jboss/as/quickstarts/ejb/multi/server/BasicRuntimeIT.java, ejb-throws-exception/web/src/test/java/org/jboss/as/quickstarts/ear/controller/BasicRuntimeIT.java, helloworld-singleton/src/test/java/org/jboss/as/quickstarts/singleton/BasicRuntimeIT.java, hibernate/src/test/java/org/jboss/as/quickstart/hibernate/BasicRuntimeIT.java, servlet-security/src/test/java/org/jboss/as/quickstarts/servlet_security/BasicRuntimeIT.java
https://issues.redhat.com/browse/WFLY-20616
=> [WFLY-20616] Correct line ending handling in BasicRuntimeIT for cross-platform stability

tasks-jsf/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-20248
=> [WFLY-20248] tasks-jsf quickstart using Glow

ee-security/pom.xml, ejb-security-programmatic-auth/pom.xml, http-custom-mechanism/custom-module/pom.xml, http-custom-mechanism/webapp/pom.xml, security-domain-to-domain/web/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-18097
=> [WFLY-18097] Replace wildfly-elytron quickstarts dependencies

.ci/openshift-ci/build-root/scripts/qs-overrides/microprofile-reactive-messaging-kafka/overridable-functions.sh, microprofile-reactive-messaging-kafka/charts/amq-operator-on-openshift.yaml, microprofile-reactive-messaging-kafka/charts/kafka-on-openshift.yaml, microprofile-reactive-messaging-kafka/helm-install-prerequisites-openshift.adoc
https://issues.redhat.com/browse/WFLY-20938
=> [WFLY-20938] Update to match latest AMQ Streams For Kafka
