- guide/GettingStarted.asciidoc
The underlines of the headings were too long; they were causing whole sections to be parsed as quote blocks, hiding images and making it difficult to read.
> Fix the MarkDown syntax of the intro

- helloworld-client-ssl/README.md
- helloworld-client-ssl/pom.xml
- helloworld-client-ssl/src/main/java/org/jboss/as/quickstarts/helloworld/BouncyIntegration.java
- helloworld-client-ssl/src/main/java/org/jboss/as/quickstarts/helloworld/HelloService.java
- helloworld-client-ssl/src/main/java/org/jboss/as/quickstarts/helloworld/HelloWorldServlet.java
- helloworld-client-ssl/src/main/webapp/WEB-INF/beans.xml
- helloworld-client-ssl/src/main/webapp/WEB-INF/web.xml
- helloworld-client-ssl/src/main/webapp/index.html
- pom.xml
This example demonstrates mutual client ssl authentication over wildfly or JBoss application server via configuring keystore, truststore and https listener. Keys and certificates for configuring wildfly standalone.conf have been generated using openSSL keytool.
> helloworld-client-ssl example to show mutual ssl auth over wildfly.

- helloworld-war-ssl/README.md
- helloworld-war-ssl/pom.xml
- helloworld-war-ssl/src/main/java/org/jboss/as/quickstarts/helloworld/BouncyIntegration.java
- helloworld-war-ssl/src/main/java/org/jboss/as/quickstarts/helloworld/HelloService.java
- helloworld-war-ssl/src/main/java/org/jboss/as/quickstarts/helloworld/HelloWorldServlet.java
- helloworld-war-ssl/src/main/webapp/WEB-INF/beans.xml
- helloworld-war-ssl/src/main/webapp/WEB-INF/jboss-web.xml
- helloworld-war-ssl/src/main/webapp/WEB-INF/web.xml
- helloworld-war-ssl/src/main/webapp/index.html
- pom.xml
This quickstart shows how to configure wildfly to enable TLS/SSL configuration for the new wildfly web-subsystem Undertow and enable mutual (two-way) SSL authentication for clients in order to secure a war application with restricted access.
Different client certificates present in security-domain truststore can be assigned different roles on the basis of `app-roles.properties` file.
Please refer README.md for help and guide.
> Securing war app with mutual(two-way) SSL configuration over wildfly.

- helloworld-mdb-propertysubstitution/README.md
- helloworld-mdb-propertysubstitution/src/main/java/org/jboss/as/quickstarts/mdb/HelloWorldQueueMDB.java
- helloworld-mdb-propertysubstitution/src/main/java/org/jboss/as/quickstarts/mdb/HelloWorldTopicMDB.java
- helloworld-mdb-propertysubstitution/src/main/java/org/jboss/as/quickstarts/servlet/HelloWorldMDBServletClient.java
- helloworld-mdb-propertysubstitution/src/main/webapp/WEB-INF/activemq-jms.xml
It seems the property substitution code disappeared from the helloworld-mdb-propertysubstitution. It was restored in the JBoss EAP 7 version of the quickstart. This pull is a cherry-pick of those fixes. 
There is an additional fix to the application context in the URL for the running application in the README file. A number of other quickstart README files also have invalid application contexts: 
`http://localhost:8080/jboss-*` instead of `http://localhost:8080/wildfly-*`
I didn't squash the commits since they were cherry-picked from the other repository, but can do that if you prefer.
> Jbeap 2670: Cherry-pick fixes from JBoss EAP helloworld-mdb-propertysubstitution quickstart

- cdi-alternative/README.md
wildfly-cdi-alternative deploys under wildfly-cdi-alternative instead of jboss-cdi-alternative. It could be accessed by http://localhost:8080/wildfly-cdi-alternative/
> FIX: replace link jboss-cdi-alternative with wildfly-cdi-alternative

- helloworld-rs/src/main/java/org/jboss/as/quickstarts/rshelloworld/JAXActivator.java
The links to http://localhost:8080/wildfly-helloworld-rs/rest/json and http://localhost:8080/wildfly-helloworld-rs/rest/xml at the index page (http://localhost:8080/wildfly-helloworld-rs/) did not work as the JAX-RS was not active.  This adds an activation class that makes them work.
> add JAX-RS activation class to make rest/* work

- ejb-security-interceptors/src/main/java/org/jboss/as/quickstarts/ejb_security_interceptors/DelegationLoginModule.java
Fix the array access for 
https://issues.jboss.org/browse/JDF-857
> [JDF-857] ejb-security-interceptors deny login delegation with a hidd ArrayIndexOutOfBounds

- resteasy-jaxrs-client/README.md
- resteasy-jaxrs-client/pom.xml
Outdated link was still pointing to "jboss-helloworld-rs"
> Fix link to helloworld-rs on resteasy-jaxrs

- helloworld/README.md
Hello. The _http://localhost:8080/jboss-helloworld_ URL provided in the README of HelloWorld quickstart generates a 404 error.
> Fixed incorrect URL in HelloWorld quickstart

- wicket-ear/README.md
- wicket-ear/ejb/src/main/java/org/jboss/as/quickstarts/wicketEar/ejbjar/dao/ContactDao.java
- wicket-ear/ejb/src/main/java/org/jboss/as/quickstarts/wicketEar/ejbjar/dao/ContactDaoBean.java
- wicket-ear/pom.xml
- wicket-ear/war/pom.xml
- wicket-ear/war/src/main/java/org/jboss/as/quickstarts/wicketEar/war/WicketJavaEEApplication.java
- wicket-ear/war/src/main/java/org/jboss/as/quickstarts/wicketEar/war/pages/ListContacts.java
- wicket-war/README.md
- wicket-war/pom.xml
- wicket-war/src/main/java/org/jboss/as/quickstarts/wicketWar/WicketJavaEEApplication.java
- wicket-war/src/main/java/org/jboss/as/quickstarts/wicketWar/dao/ContactDao.java
- wicket-war/src/main/java/org/jboss/as/quickstarts/wicketWar/dao/ContactDaoBean.java
- wicket-war/src/main/java/org/jboss/as/quickstarts/wicketWar/pages/ListContacts.java
Both WildFly Wicket quickstarts (wicket-ear, wicket-war) use Wicket version 1.5 which is not supported anymore.
Also when you run wicket-ear and try:
1. click on "Insert a new Contact" and add a new contact 
2. click on "Insert a new Contact" and then click on the browser back button, you get: ERROR [org.apache.wicket.DefaultExceptionMapper] (default task-46) Unexpected error occurred: java.lang.RuntimeException: Could not deserialize object from byte[]
This PR upgrades Wicket version to 7.3 and also fixes mentioned bug.
> wildfly-wicket quickstarts upgrade and bug fix

- greeter/README.md
- greeter/src/main/webapp/WEB-INF/web.xml
Hello, 
I followed the instructions to build and deploy the greeter app, but when I requested in my browser the URL of the app I got a 404 Not Found error. Replacing the URL with the correct one resulted in a second error - 403 Forbidden. Adding a web.xml descriptor file solved the second issue.
> Fix path and added web.xml descriptor

- jaxrs-client/pom.xml
- managedexecutorservice/pom.xml
@rafabene  or WildFly quickstart administrator: 
THIS NEEDS TESTING! DO NOT MERGE THIS UNTIL YOU TEST AND CONFIRM IT WORKS!!!
I upgraded and tested the JBoss EAP 7 quickstarts to use the new `resteasy-jackson2-provider`. This fix works there. I then cherry-picked the commit to backport the fix to the wildfly-quickstarts . 
I tried to test the fixes, however I am not set up with a WildFly server, so I tested against JBoss EAP 7. When I run the Maven tests, I get the following errors.
jaxrs-client:
Failed tests: 
ContactsRestClientTest.requestResponseFiltersTest:189 All contacts should be dropped expected:<200> but was:<405>
ContactsRestClientTest.delayedInvocationTest:154 All contacts should be dropped expected:<200> but was:<405>
ContactsRestClientTest.asyncCrudTest:89 All contacts should …
> REVIEW CAREFULLY - JBEAP-3041: Updgrade quickstarts to use the resteasy-jackson2-provider

- websocket-hello/src/main/webapp/index.html
The URL in the example is using still the jboss-websocket URL. Switched it to wildfly-websocket.
I intentionally didn't change the README as this is done in https://github.com/wildfly/quickstart/pull/115
> fixed the websocket url to use wildfly

- wsat-simple/pom.xml
Maven war plugin should define dependency on xts module for packaged war file could be deployed for configuration `standalone-xts.xml` without errors.
https://issues.jboss.org/browse/WFLY-8592
https://github.com/jbossas/eap-quickstarts/pull/34
> [WFLY-8592] adding xts dependency to wsat-simple maven war plugin

- spring-petclinic/functional-tests/src/test/java/org/jboss/as/quickstarts/spring/petclinic/test/webdriver/Deployments.java
**Motivation**
https://issues.jboss.org/browse/JBEAP-11751
See web.xml in Spring Petclinic. You can see "jpa" is set as default profile there. This PR set "jpa" as default for functional tests too.
> JBEAP-11751 - Set "jpa" as default for functional tests

- http-custom-mechanism/README.adoc
- http-custom-mechanism/configure-elytron.cli
- http-custom-mechanism/configure-security-domain.cli
- http-custom-mechanism/custom-module/add-custom-module.cli
- http-custom-mechanism/custom-module/pom.xml
- http-custom-mechanism/custom-module/remove-custom-module.cli
- http-custom-mechanism/custom-module/src/main/java/org/jboss/as/quickstart/http_custom_mechanism/CustomHeaderHttpAuthenticationMechanism.java
- http-custom-mechanism/custom-module/src/main/java/org/jboss/as/quickstart/http_custom_mechanism/CustomMechanismFactory.java
- http-custom-mechanism/custom-module/src/main/resources/META-INF/services/org.wildfly.security.http.HttpServerAuthenticationMechanismFactory
- http-custom-mechanism/pom.xml
- http-custom-mechanism/webapp/pom.xml
- http-custom-mechanism/webapp/src/main/java/org/jboss/as/quickstart/http_custom_mechanism/SecuredServlet.java
- http-custom-mechanism/webapp/src/main/webapp/WEB-INF/web.xml
- http-custom-mechanism/webapp/src/main/webapp/index.html
@ctomc: This was adapted from @darranl  blog: http://darranl.blogspot.com/
I used his source, which consisted of multiple projects and packaged so that is could all be done from the one `http-custom-mechanism` quickstart. I also changed the instructions a bit to flow with the steps you take to deploy, test, configure, retest.
I do need to add some details about the classes in the README file, but the basics are there. Let me know what you think.
> Add new custom HTTP mechanism quickstart

- jaxrs-client/pom.xml
- managed-executor-service/pom.xml
jax-rs related test fixes to run on JDK 11
QS identified via:
```bash
for i in `git grep jboss-jaxrs-api | cut -d: -f1`; do
mvn -f $i -Dmaven.compiler.target=10 -Dmaven.compiler.source=10 clean install wildfly:deploy wildfly:undeploy
read -n 1 -p "compiled and deployed $i, continue?"
mvn -f $i verify -Parq-remote
read -n 1 -p "arq-remote checked on $i, continue?"
done
```
> jax-rs related test fixes to run on JDK 11

- ejb-remote/client/pom.xml
* Adding Multi-Release: true to configuration for Maven Assembly Plugin for ejb-remote-client
> [WFLY-11035] ejb-remote quickstart fat client jar is not multi-release

- jta-crash-rec/README.adoc
A small fix in the jta crash quickstarts. There is said the JTA transaction is not distributed over multiple application severs. That's not true - see e.g. https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html/development_guide/java_transaction_api_jta#about_java_transactions_api_jta
```
The TM works in JTA transactions mode, the data is shared in memory,
and the transaction context is transferred by remote EJB calls...
```
> Fix of README.md wording in jta crash quickstarts

- shared-doc/attributes.adoc
@emmartins : This fix needs to be applied to the CD15 quickstart repo.
> Update quickstart source GitHub repo URL for CD releases

- jaxws-retail/service/pom.xml
Issue: https://issues.jboss.org/browse/WFLY-11909
Please note this PR only fixes plugin config for Windows with JDK8, JDK11 needs a plugin update or java command in PATH.
> [WFLY-11909] jaxws-tools-maven-plugin configuration fixes

- pom.xml
Issue:  https://issues.jboss.org/browse/WFLY-11909
The issue's 2nd PR, upgrades the plugin with proper support for Windows OS with JDK 11
> [WFLY-11909] upgrade jaxws-tools-maven-plugin to version 1.2.3.Final

- jts/application-component-2/src/main/resources/META-INF/jboss-ejb3.xml
Issue: https://issues.redhat.com/browse/WFLY-12797
Changes in jts quickstart to remove errors in Code Ready. Removed xsi schema location and iiop elements.
> [WFLY-12797] removing xsi schema location

- ejb-remote/README.adoc
- ejb-remote/client/pom.xml
to be comprehensible for users
https://issues.redhat.com/browse/WFLY-13169
really only a *minor* fix on restructuring of the `README.adoc`. The user for WFLY remote invocation needs to be created at the server side first and then server could be started.
> [WFLY-13169] change the position of points to add user on ejb-remote

- microprofile-metrics/README.adoc
- microprofile-metrics/grafana.json
- microprofile-metrics/pom.xml
- microprofile-metrics/prometheus.yml
- microprofile-metrics/src/main/java/org/wildfly/quickstarts/microprofile/metrics/JaxRsApplication.java
- microprofile-metrics/src/main/java/org/wildfly/quickstarts/microprofile/metrics/PrimeNumberChecker.java
- microprofile-metrics/src/test/java/org/wildfly/quickstarts/microprofile/metrics/MicroProfileMetricsIT.java
- microprofile-metrics/src/test/resources/arquillian.xml
- pom.xml
https://issues.redhat.com/browse/WFLY-12809
Branch 19.0.x
> [19.x] [WFLY-12809] Quickstart for MP Metrics 2.3

- microprofile-opentracing/README.adoc
- microprofile-opentracing/pom.xml
- microprofile-opentracing/src/main/java/org/wildfly/quickstarts/microprofile/opentracing/ExplicitlyTracedBean.java
- microprofile-opentracing/src/main/java/org/wildfly/quickstarts/microprofile/opentracing/JaxRsApplication.java
- microprofile-opentracing/src/main/java/org/wildfly/quickstarts/microprofile/opentracing/TracedResource.java
- microprofile-opentracing/src/test/java/org/wildfly/quickstarts/microprofile/opentracing/MicroProfileOpenTracingIT.java
- microprofile-opentracing/src/test/java/org/wildfly/quickstarts/microprofile/opentracing/MockTracerResolver.java
- microprofile-opentracing/src/test/resources/arquillian.xml
- pom.xml
https://issues.redhat.com/browse/WFLY-12829
> [WFLY-12829] Quickstart for MP OpenTracing 1.3

- microprofile-config/README.adoc
- microprofile-config/pom.xml
- microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/ConfigResource.java
- microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/ConverterResource.java
- microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/CustomConfigResource.java
- microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/JaxRsApplication.java
- microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/converter/MicroProfileCustomValueConverter.java
- microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/converter/type/MicroProfileCustomValue.java
- microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/custom/CustomConfigSource.java
- microprofile-config/src/main/java/org/wildfly/quickstarts/microprofile/config/custom/CustomPropertiesFileProvider.java
- microprofile-config/src/main/resources/META-INF/microprofile-config.properties
- microprofile-config/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
- microprofile-config/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSourceProvider
- microprofile-config/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter
- microprofile-config/src/main/webapp/WEB-INF/web.xml
- microprofile-config/src/main/webapp/index.jsp
- microprofile-config/src/test/java/org/wildfly/quickstarts/microprofile/config/MicroProfileConfigIT.java
- microprofile-config/src/test/resources/arquillian.xml
- pom.xml
https://issues.redhat.com/browse/WFLY-12802
> [WFLY-12802] Quickstart for MP Config 1.4

- deltaspike-authorization/pom.xml
- http-custom-mechanism/pom.xml
- microprofile-fault-tolerance/README.adoc
- microprofile-fault-tolerance/pom.xml
- microprofile-openapi/pom.xml
- pom.xml
JIRA's:
- https://issues.redhat.com/browse/WFLY-13271
- https://issues.redhat.com/browse/WFLY-13272
Note that I wasn't sure if we should target 20.0.0.Beta1-SNAPSHOT for this or 19.0.0.Final. Let me know if we prefer a snapshot or if we should wait for beta1 to change this.
> Upgrade wildfly-maven-plugin and fix WildFly version

- microprofile-opentracing/README.adoc
- shared-doc/start-the-standalone-server.adoc
https://issues.redhat.com/browse/WFLY-13467
> WFLY-13467 Issues in readme for microprofile-opentracing QS

- microprofile-jwt/src/test/java/org/wildfly/quickstarts/mpjwt/JWTClientIT.java
I think really we should better understand how the trailing slash in the injected deploymentUrl can appear but this PR makes the test tolerant to when it does happen.
https://issues.redhat.com/browse/WFLY-13472
> [WFLY-13472] Test if the injected deploymentUrl contains a trailing slash.

- jaxrs-jwt/README.adoc
- jaxrs-jwt/client/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-13620
> WFLY-13620 jaxrs-jwt: The parameters 'mainClass' are missing or invalid

- helloworld-jms/README.adoc
Issue: https://issues.redhat.com/browse/WFLY-13861
In code https://github.com/wildfly/quickstart/blob/master/helloworld-jms/src/main/java/org/jboss/as/quickstarts/jms/HelloWorldJMSClient.java#L41. The default value of `java.naming.provider.url` is more than just the hostname.
> correct default value of java.naming.provider.url in README.adoc

- http-custom-mechanism/README.adoc
- http-custom-mechanism/configure-elytron.cli
- http-custom-mechanism/configure-security-domain.cli
https://issues.redhat.com/browse/WFLY-11492
> [WFLY-11492] Quickstart http-custom-mechanism: documentation step fails

- microprofile-config/pom.xml
- microprofile-config/src/main/jkube/route.yml
- microprofile-fault-tolerance/pom.xml
- microprofile-fault-tolerance/src/main/jkube/route.yml
- microprofile-health/pom.xml
- microprofile-health/src/main/jkube/route.yml
- microprofile-jwt/pom.xml
- microprofile-jwt/src/main/jkube/route.yml
- microprofile-metrics/pom.xml
- microprofile-metrics/src/main/jkube/route.yml
- microprofile-openapi/pom.xml
- microprofile-openapi/src/main/jkube/route.yml
- microprofile-opentracing/pom.xml
- microprofile-opentracing/src/main/jkube/route.yml
- microprofile-rest-client/country-client/pom.xml
- microprofile-rest-client/country-client/src/main/jkube/route.yml
- microprofile-rest-client/country-server/pom.xml
- microprofile-rest-client/country-server/src/main/jkube/route.yml
- microprofile-rest-client/pom.xml
- shared-doc/build-and-run-the-quickstart-with-bootable-jar.adoc
* Upgrade to JKube 1.0.1
* Upgrade to Bootable JAR 2.0.0.Beta9.
* Removed api version in route.yml
* Removed java.net.preferIPv4Stack system property, automatically added by JKube.
* Use registry.redhat.io/ubi8/openjdk-11:latest image in all bootable quickstarts.
> [WFLY-13713] Bootable JAR support for MicroProfile Quickstarts, upgrade jkube to 1.0.1

- microprofile-opentracing/src/test/java/org/wildfly/quickstarts/microprofile/opentracing/MicroProfileOpenTracingIT.java
- microprofile-opentracing/src/test/java/org/wildfly/quickstarts/microprofile/opentracing/MockTracerFactory.java
* Using non depercated API.
Jira: https://issues.redhat.com/browse/WFLY-14178
> [WFLY-14178]: Deprecated using of TracerResolver.resolve() in MP OpenTracing Quickstart.

- pom.xml
Issue: https://issues.redhat.com/browse/WFLY-14173
> [WFLY-14173] set asciidoc plugin output directory to .

- microprofile-config/pom.xml
- microprofile-fault-tolerance/pom.xml
- microprofile-health/pom.xml
- microprofile-jwt/pom.xml
- microprofile-metrics/pom.xml
- microprofile-openapi/pom.xml
- microprofile-opentracing/pom.xml
- microprofile-rest-client/country-client/pom.xml
- microprofile-rest-client/country-server/pom.xml
- shared-doc/build-and-run-the-quickstart-with-bootable-jar.adoc
Issue: https://issues.redhat.com/browse/WFLY-14463
Forked CLI execution and Galleon provisioning implies much less memory consumed, required for s2i build on Openshift.
> Fix for WFLY-14463, Make bootable JAR to fork provisioning and CLI execution

- ejb-txn-remote-call/client/client-cr.yaml
- ejb-txn-remote-call/client/pom.xml
- ejb-txn-remote-call/server/pom.xml
- ejb-txn-remote-call/server/server-cr.yaml
https://issues.redhat.com/browse/WFLY-12904
Fixing s2i build issue for the quickstart. The s2i works only with the context dir project which is an issue for this multi module quickstart. With that the quickstart does not publish all artifacts to maven central and thus issue with dependency lookup happens in s2i build.
> [WFLY-12904] s2i build fix for quickstart ejb-txn-remote-call

- ejb-txn-remote-call/README.adoc
- shared-doc/attributes.adoc
https://issues.redhat.com/browse/WFLY-12904
23.x PR: https://github.com/wildfly/quickstart/pull/482
> [WFLY-12904] using eap-basic-s2i for EAP instead of eap74-basic-s2i

- contacts-jquerymobile/functional-tests/src/test/resources/arquillian.xml
- helloworld-html5/functional-tests/src/test/resources/arquillian.xml
- kitchensink-angularjs/functional-tests/src/test/resources/arquillian.xml
- spring-greeter/functional-tests/src/test/resources/arquillian.xml
- spring-kitchensink-basic/functional-tests/src/test/resources/arquillian.xml
- spring-kitchensink-springmvctest/functional-tests/src/test/resources/arquillian.xml
Issue: https://issues.redhat.com/browse/WFLY-14720
This partial fix of the issue updates all Quickstarts functional tests to use PhantomJS WebDriver browser, instead of Firefox, which recent versions have issues with Arquillian Graphene.
> [WFLY-14720] move web functional tests to phantomjs browser

- tasks-jsf/src/main/java/org/jboss/as/quickstarts/tasksJsf/FacesConfiguration.java
- tasks-jsf/src/main/java/org/jboss/as/quickstarts/tasksJsf/Resources.java
This will fix https://issues.redhat.com/browse/WFLY-14827.
Currently it is necessary to either write an external Injection Point per JSF-specific injections points like @FacesContext or similiar.
Or you can use a class which is annotated with @FacesConfig which will give you the expected behaviour like in the docs.
In this PR a dedicated configuration class is used to activate JSF 2.3 features in JBoss EAP 7.3
Injection points like FacesContext and ExternalContext work out of the box in JBoss EAP 7.3 with this class.
No manual CDI Produces are necessary and JSF 2.3 works like described in the JSF docs.
> [WFLY-14827] Add an explicit FacesConfiguration class

- microprofile-config/pom.xml
- microprofile-fault-tolerance/pom.xml
- microprofile-health/pom.xml
- microprofile-jwt/pom.xml
- microprofile-metrics/pom.xml
- microprofile-openapi/pom.xml
- microprofile-opentracing/pom.xml
- microprofile-reactive-messaging-kafka/pom.xml
- microprofile-rest-client/pom.xml
- todo-backend/pom.xml
In addition upgraded wildfly-datasources-galleon-pack to 2.0.2.Final
> Fix for WFLY-14911, Upgrade quickstarts to use Bootable JAR plugin 5.0.0.Final

- microprofile-opentracing/README.adoc
- microprofile-opentracing/pom.xml
https://issues.redhat.com/browse/WFLY-15005
There are incompatible changes in new io.opentracing artifacts so we need to use the updated ones (matching the ones included in server) for QS to work - some context https://github.com/opentracing/opentracing-java/issues/374
> [WFLY-15005] Update io.opentracing dependencies to match server version

- shared-doc/attributes.adoc
Set its value to EAP_7.4.0.GA
JIRA: https://issues.redhat.com/browse/WFLY-15074
> [WFLY-15074] Fix EAPQuickStartRepoTag doc attribute

- pom.xml
Based on a reported issue [WFLY-13908](https://issues.redhat.com/browse/WFLY-13908) Eclipse m2e mapping for checkstyle uses version 8.35, while quickstart uses version 8.5 with maven CLI. As a result, running inside Eclipse has the error _(with any checkstyle >= 8.19)_: TreeWalker has no cacheFile property.
This checkstyle config was updated in wildfly-config-checkstyle 1.0.8.Final to be >= 8.19 compatible, therefore an update of pom.xml is needed to be aligned with latest wildfly checkstyle config.
> [WFLY-13908] pom.xml wildfly-checkstyle-config update to 1.0.8.Final

- microprofile-config/pom.xml
- microprofile-fault-tolerance/pom.xml
- microprofile-health/pom.xml
- microprofile-jwt/pom.xml
- microprofile-metrics/pom.xml
- microprofile-openapi/pom.xml
- microprofile-opentracing/pom.xml
- microprofile-reactive-messaging-kafka/pom.xml
- microprofile-rest-client/pom.xml
- todo-backend/pom.xml
@emmartins , this upgrade will be required for 26 Beta1. NB: no Bootable JAR plugin will be released for 26 Beta1, so 6.1.1.Final is the release to use.
> Upgrade qs to bootable JAR 6.1.1.Final

- ha-singleton-deployment/README.adoc
- ha-singleton-deployment/src/main/java/org/jboss/as/quickstarts/ha/singleton/SingletonTimer.java
Resolves
https://issues.redhat.com/browse/WFLY-16350
> WFLY-16350 Conscious Language in ha-singleton-deployment quickstart

- jaxws-retail/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-16212
> [WFLY-16212] QS jaxws-retail is using broken version of jaxws-tools-maven-plugin

- microprofile-metrics/src/test/resources/arquillian.xml
- pom.xml
https://issues.redhat.com/browse/WFLY-17194
Enable microprofile-metrics module
Remove explicit protocol config so the correct default is used
> [WFLY-17194] Verify and enable the the microprofile-metrics quickstart

- microprofile-config/pom.xml
- microprofile-fault-tolerance/pom.xml
- microprofile-health/pom.xml
- microprofile-jwt/pom.xml
- microprofile-metrics/pom.xml
- microprofile-openapi/pom.xml
- microprofile-opentracing/pom.xml
- microprofile-reactive-messaging-kafka/pom.xml
- microprofile-rest-client/pom.xml
- todo-backend/pom.xml
for all quickstarts that uses Bootable Jar.
> Update wildly-jar-maven-plugin to 8.0.1.Final

- microprofile-health/pom.xml
- pom.xml
Upsate wildlfy-jar-maven-plugin to 8.0.1.Final to be able to build the Bootable Jar version of the quickstart
JIRA: https://issues.redhat.com/browse/WFLY-17189
> [WFLY-17189] Re-enable the the microprofile-health quickstart

- ejb-txn-remote-call/README.adoc
- ejb-txn-remote-call/client/configuration/custom-config.xml
- ejb-txn-remote-call/client/extensions/remote-configuration.cli
https://issues.redhat.com/browse/WFLY-16764
> [WFLY-16764] Migrate ejb-txn-remote-call quickstart from legacy security to elytron

- dist/src/main/assembly/assembly.xml
- logging/configure-logging.cli
- logging/pom.xml
- logging/remove-logging.cli
- pom.xml
https://issues.redhat.com/browse/WFLY-17535
The first commit simply re-enables the quickstart. The second commit does some minor cleanup.
> [WFLY-17535]  Re-enable the logging quickstart

- helloworld-jms/README.adoc
- pom.xml
* Re-enabling helloworld-jms quickstart.
Jira: https://issues.redhat.com/browse/WFLY-17526
> [WFLY-17526] Verify and re-enable helloworld-jms quickstart.

- dist/src/main/assembly/assembly.xml
- pom.xml
- wsat-simple/README.adoc
- wsat-simple/configure-server.cli
- wsat-simple/pom.xml
- wsat-simple/restore-configuration.cli
- wsat-simple/src/main/java/org/jboss/as/quickstarts/wsat/simple/MockRestaurantManager.java
- wsat-simple/src/main/webapp/WEB-INF/beans.xml
- wsat-simple/src/main/webapp/WEB-INF/classes/context-handlers.xml
- wsat-simple/src/main/webapp/WEB-INF/jboss-web.xml
- wsat-simple/src/test/java/org/jboss/as/quickstarts/wsat/simple/ClientIT.java
- wsat-simple/src/test/resources/arquillian.xml
- wsat-simple/src/test/resources/context-handlers.xml
- wsba-coordinator-completion-simple/README.adoc
- wsba-coordinator-completion-simple/configure-server.cli
- wsba-coordinator-completion-simple/pom.xml
- wsba-coordinator-completion-simple/restore-configuration.cli
- wsba-coordinator-completion-simple/src/test/java/org/jboss/as/quickstarts/wsba/coordinatorcompletion/simple/ClientIT.java
- wsba-coordinator-completion-simple/src/test/resources/arquillian.xml
- wsba-participant-completion-simple/README.adoc
- wsba-participant-completion-simple/configure-server.cli
- wsba-participant-completion-simple/pom.xml
- wsba-participant-completion-simple/restore-configuration.cli
- wsba-participant-completion-simple/src/main/java/META-INF/beans.xml
- wsba-participant-completion-simple/src/test/java/org/jboss/as/quickstarts/wsba/participantcompletion/simple/ClientIT.java
- wsba-participant-completion-simple/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/WFLY-17530
https://issues.redhat.com/browse/WFLY-17531
https://issues.redhat.com/browse/WFLY-17532
updated READMEs
JBOSS configuration must be in standalone/configuration folder 
updated dependencies
set bean-discovery to all
> WFLY-17530, WFLY-17531, WFLY-17532 re-enable xts quickstarts

- .github/workflows/quickstart_bmt_ci .yml
- bmt/README.adoc
- bmt/charts/helm.yaml
- bmt/pom.xml
- bmt/src/test/java/org/wildfly/quickstarts/cmt/BasicRuntimeIT.java
link: https://issues.redhat.com/browse/WFLY-18460 
Note: Openshift test fails because in the current quickstart (main branch) there isn't the provisioned-server profile, so the build-artifact step will fail. To work it around you could test this PR locally changing the helm.yaml file with:
```
build:
uri: https://github.com/marcosgopen/quickstart-wildfly.git
ref: WFLY-18460
contextDir: bmt
deploy:
replicas: 1
```
Once the PR is merged this issue gets solved.
> [WFLY-18460] bmt Quickstart Common Enhancements CY2023Q3

- .github/workflows/quickstart_spring-resteasy_ci.yml
- spring-resteasy/README.adoc
- spring-resteasy/charts/helm.yaml
- spring-resteasy/pom.xml
- spring-resteasy/src/test/java/org/jboss/as/quickstarts/resteasyspring/test/BasicRuntimeIT.java
- spring-resteasy/src/test/java/org/jboss/as/quickstarts/resteasyspring/test/ResteasySpringIT.java
https://issues.redhat.com/browse/WFLY-18508
> WFLY-18508 spring-resteasy Quickstart Common Enhancements CY2023Q3

- .github/workflows/quickstart_ci.yml
- .github/workflows/quickstart_spring-resteasy_ci.yml
Issue: https://issues.redhat.com/browse/WFLY-18689
> [WFLY-18689] adds matrix.jdk customization, fixes add-users feature

- spring-resteasy/pom.xml
The `feature pack` configuration is unnecessary because it's already included in WildFly.
> remove unnecessary resteasy spring feature pack configuration

- .github/workflows/quickstart_mail_ci.yml
- .github/workflows/quickstart_mail_ci_before.sh
- mail/README.adoc
- mail/configure-mail-session.cli
- mail/docker-compose.yaml
- mail/mail-server-conf/imapserver.xml
- mail/mail-server-conf/pop3server.xml
- mail/mail-server-conf/smtpserver.xml
- mail/pom.xml
- mail/src/main/java/org/jboss/as/quickstarts/mail/Email.java
- mail/src/main/webapp/WEB-INF/beans.xml
- mail/src/main/webapp/home.xhtml
- mail/src/main/webapp/resources/css/main.css
- mail/src/test/java/org/jboss/as/quickstarts/mail/BasicRuntimeIT.java
- mail/src/test/java/org/jboss/as/quickstarts/mail/MailTestCaseIT.java
Jira issue: https://issues.redhat.com/browse/WFLY-18491
Initially, as a draft to test the CI, and without OpenShift stuff yet.
> [WFLY-18491] Mail Quickstart Common Enhancements

- .github/workflows/quickstart_jts_ci.yml
- jts/README.adoc
- jts/pom.xml
https://issues.redhat.com/browse/WFLY-18488
The changes include clarifying the test setup and disabling testing on Openshift since setting up and coordinating multiple servers is not technically feasible without incurring a lot of effort.
> WFLY-18488 jts Quickstart Common Enhancements CY2023Q3

- .github/workflows/quickstart_websocket-endpoint_ci.yml
- websocket-endpoint/README.adoc
- websocket-endpoint/charts/helm.yaml
- websocket-endpoint/pom.xml
- websocket-endpoint/src/test/java/org/jboss/quickstarts/websocket_endpoint/BasicRuntimeIT.java
- websocket-endpoint/src/test/java/org/jboss/quickstarts/websocket_endpoint/BidWebSocketEndpointIT.java
- websocket-endpoint/src/test/java/org/jboss/quickstarts/websocket_endpoint/EchoListener.java
Issue: https://issues.redhat.com/browse/WFLY-18513
> [WFLY-18513] websocket-endpoint quickstart enhancement CY2023Q3

- microprofile-rest-client/README.adoc
- microprofile-rest-client/pom.xml
- microprofile-rest-client/src/test/java/org/wildfly/quickstarts/microprofile/rest/client/CountriesResource.java
Issue: https://issues.redhat.com/browse/WFLY-18499
Followup of #780, reworks the README:
- Removes from scratch content that was outdated
- Adds 2 sections wrt accessing the app, and wrt the rest client
> [WFLY-18499] mp rest-client README rework

- shared-doc/run-integration-tests-with-provisioned-server.adoc
@emmartins  re-opening this issue, please read the comment in Jira
Issue: https://issues.redhat.com/browse/WFLY-18814
> [WFLY-18814] fixed typo - server.host instead of jbossHome

- .ci/openshift-ci/build-root/scripts/openshift-test-runner.sh
If it works, this is better than https://github.com/wildfly/quickstart/pull/822
> Don't run OpenShift CI if there is no charts/ dir for the QS

- .ci/openshift-ci/build-root/scripts/overridable-functions.sh
- .ci/openshift-ci/build-root/scripts/qs-overrides/microprofile-lra/overridable-functions.sh
- .ci/openshift-ci/build-root/scripts/run-quickstart-test-on-openshift.sh
- microprofile-lra/README.adoc
- microprofile-lra/charts/helm.yaml
- shared-doc/helm-deploy-project.adoc
- shared-doc/run-integration-tests-with-openshift.adoc
Issue: [WFLY-18901](https://issues.redhat.com/browse/WFLY-18901)
> Disable TLS in LRA quickstart

- .github/workflows/quickstart_ci.yml
- .github/workflows/quickstart_ejb-throws-exception_ci.yml
Otherwise mvn wildfly:start fails on resolving dependencies in the ear module
> Ears need to use install to populate the mvn repo

- dist/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-18956
Branch 31.x
> [31.x] [WFLY-18956] Adds sha1 digest to dist module's zip files

- .ci/openshift-ci/build-root/scripts/excluded-directories.txt
- .ci/openshift-ci/build-root/scripts/qs-overrides/micrometer/overridable-functions.sh
- micrometer/README-source.adoc
- micrometer/charts/opentelemetry-collector.yaml
- micrometer/configure-micrometer.cli
- micrometer/helm-install-prerequisites.adoc
- micrometer/pom.xml
Clean up YAML
Add instructions for install otel collector on OS
OpenShift CI setup
Issues: [WFLY-15842](https://issues.redhat.com/browse/WFLY-15842) , [WFLY-17678](https://issues.redhat.com/browse/WFLY-17678) ,
> [WFLY-17678] [WFLY-18942] Micrometer QS on OpenShift

- .github/workflows/quickstart_ejb-multi-server_ci.yml
- ejb-multi-server/README-source.adoc
- ejb-multi-server/README.adoc
- ejb-multi-server/app-main/ear/pom.xml
- ejb-multi-server/app-one/ear/pom.xml
- ejb-multi-server/app-two/ear/pom.xml
- ejb-multi-server/app-web/pom.xml
- ejb-multi-server/app-web/src/test/java/org/jboss/as/quickstarts/ejb/multi/server/BasicRuntimeIT.java
- ejb-multi-server/deploy-domain.cli
- ejb-multi-server/install-domain.cli
- ejb-multi-server/pom.xml
- ejb-multi-server/undeploy-domain.cli
- shared-doc/build-and-deploy-the-quickstart.adoc
- shared-doc/openshift-incompatibility.adoc
- shared-doc/run-integration-tests-with-server-distribution.adoc
Issue: https://issues.redhat.com/browse/WFLY-18464
Changes on top of  #842:
* Renamed workflow to correct filename: quickstart_ejb-multi-server_ci.yml
* Moved workflow to correct directory: /.github/workflows (not ejb-multi-server/.github/workflows) 
* Fixed content in the workflow
* Replaced custom sections in README with includes for related ones in shared-docs, wrt deploy and undeploy (and removed ref to standalone start in that deploy section)
* Added include of integration tests section from shared-docs (and added customization of test sources dir in it)
* Removed unused cli scripts to deploy and undeploy domain
* Fixed plugin management for wildfly maven plugin
* Updated server.version value
> [WFLY-18464] ejb-multi-server Quickstart Common Enhancements CY2023Q3

- helloworld-mutual-ssl/README-source.adoc
- helloworld-mutual-ssl/pom.xml
- helloworld-mutual-ssl/src/test/java/org/jboss/as/quickstarts/helloworld_mutual_ssl/BasicRuntimeIT.java
- shared-doc/run-integration-tests-with-provisioned-server.adoc
- shared-doc/run-integration-tests-with-server-distribution.adoc
Issue: https://issues.redhat.com/browse/WFLY-18476
Changes:
* Moves README.adoc to README-source.adoc
* Moves section set_up_client_keystore_using_java_keytool to after the server is started
* Adds extraStandardDistTestParams and extraProvisioningTestParams extension points to add extra testing params
* Removes include for outdated sections wrt IDEs and debug
* Syncs pom version properties
* Moves http-client dependency to manged version, and test scope
* Simplifies basic test usage of a server.dir property
> [WFLY-18476] Additional fixes/enhancements

- microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/Coffee.java
- microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeRepositoryService.java
- microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeResource.java
- microprofile-fault-tolerance/src/test/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeResourceIT.java
https://issues.redhat.com/browse/WFLY-17740
In this issue were added two Test methods, both testing a method with @Fallback annotation . The first one tests the successful execution of the method, which also has specific time frame (with the help of @Timeout). The second one secures that every time the execution time of the method exceeds the time limit, the Fallback method executed successfully.
> [WFLY-17740] Add missing @fallback test in Microprofile Fault Tolerance quickstart

- microprofile-reactive-messaging-kafka/README-source.adoc
Issue: https://issues.redhat.com/browse/WFLY-19358
Downstream PR: https://github.com/jbossas/eap-quickstarts/pull/262
> [JBEAP-27122] kafka is not supported on Windows note

- microprofile-reactive-messaging-kafka/README-source.adoc
Issue: https://issues.redhat.com/browse/WFLY-19359
Downstream PR: https://github.com/jbossas/eap-quickstarts/pull/263
> [WFLY-19359] bootable jar with kafka can produce a warning message

- .github/workflows/quickstart_ha-singleton-deployment_ci.yml
- ha-singleton-deployment/README-source.adoc
- ha-singleton-deployment/pom.xml
- ha-singleton-deployment/singleton-deployment-overlay-add.cli
- ha-singleton-deployment/src/main/webapp/index.html
- ha-singleton-deployment/src/test/java/org/wildfly/quickstarts/ha/singleton/BasicRuntimeIT.java
* Synchronize properties definitions.
* Convert the deployment to war from jar and introduce a welcome page via static index.html.
* Introduce a simple integration test and -Pintegration-testing Maven profile.
* Cleanup README file.
* Introduce automatic CI for the quickstart.
n.b. no OpenShift support and no bootable-jar support.
Resolves
https://issues.redhat.com/browse/WFLY-18471 – ha-singleton-deployment Quickstart Common Enhancements CY2023Q3
Related PR for ha-singleton-service QS: https://github.com/wildfly/quickstart/pull/915 (not conflicting)
> WFLY-18471 ha-singleton-deployment Quickstart Common Enhancements CY2023Q3

- .ci/openshift-ci/build-root/scripts/qs-overrides/microprofile-reactive-messaging-kafka/overridable-functions.sh
- microprofile-reactive-messaging-kafka/README-source.adoc
- microprofile-reactive-messaging-kafka/charts/amq-operator-on-openshift.yaml
- microprofile-reactive-messaging-kafka/charts/kafka-on-openshift.yaml
- microprofile-reactive-messaging-kafka/helm-install-prerequisites.adoc
https://issues.redhat.com/browse/WFLY-19408
Define AMQ stream operator, instance and topic in a  yaml file for OpenShift and update the README.
> [WFLY-19359] define kafka yaml file for OpenShift and update the README.

- ha-singleton-deployment/README-source.adoc
- ha-singleton-deployment/singleton-deployment-overlay-add.cli
- ha-singleton-deployment/singleton-deployment-overlay-remove.cli
* [WFLY-19766](https://issues.redhat.com/browse/WFLY-19766) Quickstarts: ha-singleton-deployment redeploy-affected results in 'Deployment overlay singleton-deployment does not exist.'
*  rework executable segments to be runnable; 
* cleanup; 
* language fixes.
> WFLY-19766 Quickstarts: ha-singleton-deployment redeploy-affected results in 'Deployment overlay singleton-deployment does not exist.'

- .github/workflows/project_ci.yml
- .github/workflows/quickstart_ci.yml
- .github/workflows/quickstart_ejb-txn-remote-call_ci.yml
- helloworld-mutual-ssl-secured/pom.xml
- helloworld-mutual-ssl/pom.xml
- jaxrs-client/pom.xml
- jaxrs-jwt/pom.xml
- logging/pom.xml
- micrometer/pom.xml
- microprofile-config/README-source.adoc
- microprofile-config/pom.xml
- microprofile-fault-tolerance/README-source.adoc
- microprofile-fault-tolerance/pom.xml
- microprofile-health/README-source.adoc
- microprofile-health/pom.xml
- microprofile-jwt/README-source.adoc
- microprofile-jwt/pom.xml
- microprofile-lra/README-source.adoc
- microprofile-lra/pom.xml
- microprofile-openapi/pom.xml
- microprofile-reactive-messaging-kafka/README-source.adoc
- microprofile-reactive-messaging-kafka/pom.xml
- microprofile-rest-client/pom.xml
- opentelemetry-tracing/pom.xml
Issues: https://issues.redhat.com/browse/WFLY-19464, https://issues.redhat.com/browse/WFLY-19779
> [WFLY-19464] [WFLY-19779]

- .github/workflows/project_ci.yml
- .github/workflows/quickstart_ci.yml
- .github/workflows/quickstart_ejb-txn-remote-call_ci.yml
- .github/workflows/quickstart_spring-resteasy_ci.yml
Issue: https://issues.redhat.com/browse/WFLY-19879
> [WFLY-19879] drops Java 11 from Quickstarts Git Hub Workflows

- .github/workflows/quickstart_helloworld_ci.yml
- helloworld/README-source.adoc
- helloworld/pom.xml
Issue: https://issues.redhat.com/browse/WFLY-19823
> [WFLY-19823] adds bootable jar support to helloworld

- helloworld-ws/README.adoc
- helloworld-ws/src/main/webapp/WEB-INF/jboss-web.xml
- helloworld-ws/src/test/java/org/jboss/as/quickstarts/wshelloworld/ClientIT.java
https://issues.redhat.com/browse/WFLY-19662
> [WFLY-19662] Switch from / to helloworld-ws context in QS

- .github/workflows/scripts/kubernetes/core/run-quickstart-test-on-kubernetes.sh
- logging/pom.xml
- logging/src/test/java/org/jboss/as/quickstarts/logging/LogIT.java
https://issues.redhat.com/browse/WFLY-20000
https://issues.redhat.com/browse/WFLY-19999
> [WFLY-19999][WFLY-20000] Kubernetes Ci fixes

- mail/docker-compose.yaml
when using podman volumes don't get correctly mapped and missing file warning arises
> fix mail QS volume permissions

- jta-crash-rec/pom.xml
https://issues.redhat.com/browse/WFLY-20153
With this pluginManagement configuration, maven can again resolve `wildfly:deploy` goal
> [WFLY-20153] Add missing wildfly-maven-plugin configuration

- ejb-txn-remote-call/README-source.adoc
[JBEAP-29234](https://issues.redhat.com/browse/JBEAP-29234)
> [JBEAP-29234] OpenShift instructions updated

- messaging-clustering-singleton/README-source.adoc
Issue: https://issues.redhat.com/browse/JBEAP-29393
> [JBEAP-29393] Render server provisioning README content for all releases

- shared-doc/build-and-run-the-quickstart-with-bootable-jar.adoc
- shared-doc/build-and-run-the-quickstart-with-provisioned-server.adoc
- shared-doc/build-the-quickstart-for-cloud-platform-internal.adoc
Issue: https://issues.redhat.com/browse/JBEAP-29478
> [JBEAP-29478] Render proper provisioning/bootable-jar XML config snippet

- microprofile-reactive-messaging-kafka/pom.xml
- microprofile-reactive-messaging-kafka/src/main/java/org/wildfly/quickstarts/microprofile/reactive/messaging/MessagingBean.java
- microprofile-reactive-messaging-kafka/src/main/java/org/wildfly/quickstarts/microprofile/reactive/messaging/UserMessagingBean.java
Also fix BroadcastPublisher.onError()
https://issues.redhat.com/browse/WFLY-20383
> [WFLY-20383] Get rid of compiler warnings

- http-custom-mechanism/README-source.adoc
Issue: https://issues.redhat.com/browse/WFLY-20447
While going through this quickstart I probably found some mistakes in the readme.
- wrong path (.../modules/modules/...)
- one section is copy pasted and is twice in the text
- no mention of the restoring scripts
Also bit off topic, but how exactly does the password validation work for the custom mechanism, given that `X-PASSWORD` could be anything and response is still OK (200) (unlike the `X-USERNAME`)
> [WFLY-20447] Fix mistakes in "http custom mechanism" readme

- helloworld-jms/pom.xml
Fixing the helloworld-jms quickstart to use Glow.
Issue: https://issues.redhat.com/browse/WFLY-20130
> [WFLY-20130]: helloworld-jms logs missing.

- ejb-txn-remote-call/README-source.adoc
Issue: https://issues.redhat.com/browse/JBEAP-29781
> [JBEAP-29781] fix OpenShift operator uninstall instructions

- ejb-txn-remote-call/README-source.adoc
Clone https://github.com/jbossas/eap-quickstarts/pull/301
> Added missing instructions

- mail/pom.xml
- mail/src/test/java/org/jboss/as/quickstarts/mail/MailTestCaseIT.java
https://issues.redhat.com/browse/WFLY-20129
> [WFLY-20129] Mail QS tests - Use HtmlUnit instead of Selenium

- .github/dependabot.yml
Syncing the dependabot config with wildfly/wildfly... 
A couple of changes specific to this repo:
* maven dep updates scanning should be done on all dirs, not just /
* wildfly/wildfly specific ignores removed
> Sync dependabot config with wildfly/wildfly

- opentelemetry-tracing/src/main/resources/META-INF/microprofile-config.properties
https://issues.redhat.com/browse/WFLY-20924
Add MP Config file to enable otel SDK under MP
> WFLY-20924 - OpenTelemetry Quickstart doesn't function correctly under MicroProfile config
